-- ============================================================================
-- local_account_reset_final_test.sql
-- Manhaji — LOCAL final-testing account reset (XAMPP MySQL, db: manhaji_db)
--
-- WHAT THIS DOES
--   * Deletes ALL existing user accounts (users + admins/teachers/parents/
--     students) and their activity rows (attempts, progress, ...).
--   * Inserts a clean, known account set with bcrypt hashes generated by the
--     backend's own BCryptPasswordEncoder ($2a$, strength 10).
--   * Creates one active teacher_assignments row per teacher (grade 1).
--
-- WHAT THIS NEVER TOUCHES
--   * subjects, lessons, questions, quiz_questions, LESSON quizzes,
--     schools, subscriptions  (curriculum/content is preserved).
--   * No DROP DATABASE. No TRUNCATE. All statements are transactional DELETEs
--     and INSERTs on InnoDB.
--
-- SAFETY
--   * Runs inside ONE transaction: any failure rolls everything back.
--   * Idempotent: safe to re-import; it always converges to the same state.
--   * BACKUP FIRST and STOP the Spring Boot backend before importing:
--       /Applications/XAMPP/xamppfiles/bin/mysqldump \
--         -u root --socket=/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock \
--         --single-transaction --triggers --routines \
--         --default-character-set=utf8mb4 \
--         manhaji_db > ~/Desktop/manhaji_db_backup_$(date +%Y%m%d_%H%M%S).sql
--
-- ACCOUNTS CREATED (plain passwords for local login testing):
--   admin@manhaji.local            / Admin123!
--   teacher.arabic@manhaji.local   / Teacher123!   (اللغة العربية, grade 1)
--   teacher.islamic@manhaji.local  / Teacher123!   (التربية الإسلامية, grade 1)
--   teacher.math@manhaji.local     / Teacher123!   (الرياضيات, grade 1)
--   teacher.english@manhaji.local  / Teacher123!   (English, grade 1)
--   parent@manhaji.local           / Parent123!
--   student01..student10@manhaji.local / Student123!  (grade 1, linked to parent)
--
-- AFTER IMPORT
--   * Restart the Spring Boot backend and log in fresh (old JWTs reference
--     deleted user ids).
--   * Do NOT set MANHAJI_REPLACE_DEMO_ACCOUNTS (it deletes admin@manhaji.local
--     and parent@manhaji.local).
--   * Leave MANHAJI_DEMO_SEED unset (it would add a parallel *.edu account set).
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;   -- keep FK protection ON; order below is FK-safe

START TRANSACTION;

-- ----------------------------------------------------------------------------
-- 0) Ensure a school exists (reuses existing school id if present)
-- ----------------------------------------------------------------------------
INSERT INTO schools (name, address)
SELECT 'مدرسة منهاجي النموذجية', 'بيئة اختبار محلية'
WHERE NOT EXISTS (SELECT 1 FROM schools);

SET @school_id := (SELECT MIN(id) FROM schools);

-- Resolve grade-1 subject ids BY NAME (never hardcoded).
-- NOTE: the English subject row is stored as 'English' in this DB.
SET @subj_arabic  := (SELECT id FROM subjects WHERE grade_level = 1 AND name IN ('اللغة العربية', 'Arabic')                LIMIT 1);
SET @subj_islamic := (SELECT id FROM subjects WHERE grade_level = 1 AND name IN ('التربية الإسلامية', 'Islamic Education') LIMIT 1);
SET @subj_math    := (SELECT id FROM subjects WHERE grade_level = 1 AND name IN ('الرياضيات', 'Math', 'Mathematics')       LIMIT 1);
SET @subj_english := (SELECT id FROM subjects WHERE grade_level = 1 AND name IN ('English', 'اللغة الإنجليزية')            LIMIT 1);

-- ----------------------------------------------------------------------------
-- 1) DELETE existing account + activity rows (FK-safe order, accounts only)
-- ----------------------------------------------------------------------------
DELETE FROM student_responses;                 -- FK -> attempts
DELETE FROM attempts;                          -- FK -> students, quizzes
DELETE FROM progress;                          -- FK -> students, lessons
DELETE FROM skill_mastery;                     -- FK -> students, subjects
DELETE FROM learning_paths;                    -- FK -> students
DELETE FROM progress_reports;                  -- FK -> students

-- PERSONALIZED quizzes belong to (deleted) students; LESSON quizzes are
-- curriculum and are preserved. (Currently 0 personalized rows — harmless.)
DELETE qq FROM quiz_questions qq
  JOIN quizzes q ON q.id = qq.quiz_id
 WHERE q.quiz_type = 'PERSONALIZED';
DELETE FROM quizzes WHERE quiz_type = 'PERSONALIZED';

DELETE FROM teacher_assignments;               -- FK -> teachers, subjects
DELETE FROM students;                          -- FK -> users, parents, schools
DELETE FROM parents;                           -- FK -> users
DELETE FROM teachers;                          -- FK -> users
DELETE FROM admins;                            -- FK -> users
DELETE FROM audit_logs;                        -- no FK; logs reference old admin ids
DELETE FROM users;

-- ----------------------------------------------------------------------------
-- 2) ADMIN  (id 101)   admin@manhaji.local / Admin123!
-- ----------------------------------------------------------------------------
INSERT INTO users (id, role, created_at, email, full_name, is_active, last_login_at, password_hash, phone) VALUES
(101, 'ADMIN', NOW(6), 'admin@manhaji.local', 'مشرف النظام', b'1', NULL,
 '$2a$10$saqjjeSNymVkGnwqTSD8f.abiw9MRZPdv/8YB0tNK8IaXlepXXYFe', NULL);
INSERT INTO admins (id, permissions) VALUES (101, 'ALL');

-- ----------------------------------------------------------------------------
-- 3) TEACHERS (ids 111-114) — all Teacher123!
-- ----------------------------------------------------------------------------
INSERT INTO users (id, role, created_at, email, full_name, is_active, last_login_at, password_hash, phone) VALUES
(111, 'TEACHER', NOW(6), 'teacher.arabic@manhaji.local',  'أ. سلمى — معلمة اللغة العربية',     b'1', NULL, '$2a$10$MxB3ICnGDK2T.slSsenV6eEb2frOAvOj3oPtMt4gJmkh69GfU4QEW', NULL),
(112, 'TEACHER', NOW(6), 'teacher.islamic@manhaji.local', 'أ. مريم — معلمة التربية الإسلامية', b'1', NULL, '$2a$10$MxB3ICnGDK2T.slSsenV6eEb2frOAvOj3oPtMt4gJmkh69GfU4QEW', NULL),
(113, 'TEACHER', NOW(6), 'teacher.math@manhaji.local',    'أ. خالد — معلم الرياضيات',          b'1', NULL, '$2a$10$MxB3ICnGDK2T.slSsenV6eEb2frOAvOj3oPtMt4gJmkh69GfU4QEW', NULL),
(114, 'TEACHER', NOW(6), 'teacher.english@manhaji.local', 'أ. ليلى — معلمة اللغة الإنجليزية',  b'1', NULL, '$2a$10$MxB3ICnGDK2T.slSsenV6eEb2frOAvOj3oPtMt4gJmkh69GfU4QEW', NULL);

INSERT INTO teachers (id, department, assigned_grade, school_id) VALUES
(111, 'اللغة العربية',     1, @school_id),
(112, 'التربية الإسلامية', 1, @school_id),
(113, 'الرياضيات',         1, @school_id),
(114, 'اللغة الإنجليزية',  1, @school_id);

-- One ACTIVE subject assignment per teacher (backend enforcement reads this).
INSERT INTO teacher_assignments (created_at, grade_level, is_active, school_id, subject_id, teacher_id) VALUES
(NOW(6), 1, b'1', @school_id, @subj_arabic,  111),
(NOW(6), 1, b'1', @school_id, @subj_islamic, 112),
(NOW(6), 1, b'1', @school_id, @subj_math,    113),
(NOW(6), 1, b'1', @school_id, @subj_english, 114);

-- ----------------------------------------------------------------------------
-- 4) PARENT (id 121)   parent@manhaji.local / Parent123!
-- ----------------------------------------------------------------------------
INSERT INTO users (id, role, created_at, email, full_name, is_active, last_login_at, password_hash, phone) VALUES
(121, 'PARENT', NOW(6), 'parent@manhaji.local', 'ولي أمر الطلاب', b'1', NULL,
 '$2a$10$dPmM1ZDYR9o0hTDz0.KL1.YMgPX1Fgd2BOQWodTxuNDbytosHPNRC', NULL);
INSERT INTO parents (id) VALUES (121);

-- ----------------------------------------------------------------------------
-- 5) STUDENTS (ids 131-140) — grade 1, all Student123!, linked to the parent
--    Mild variety in points/streak/last_login so dashboards are not all zero.
-- ----------------------------------------------------------------------------
INSERT INTO users (id, role, created_at, email, full_name, is_active, last_login_at, password_hash, phone) VALUES
(131, 'STUDENT', NOW(6), 'student01@manhaji.local', 'ليان أحمد',   b'1', NOW(6) - INTERVAL 1 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(132, 'STUDENT', NOW(6), 'student02@manhaji.local', 'آدم محمد',    b'1', NOW(6) - INTERVAL 2 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(133, 'STUDENT', NOW(6), 'student03@manhaji.local', 'جنى خالد',    b'1', NOW(6) - INTERVAL 3 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(134, 'STUDENT', NOW(6), 'student04@manhaji.local', 'يوسف سمير',   b'1', NOW(6) - INTERVAL 5 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(135, 'STUDENT', NOW(6), 'student05@manhaji.local', 'تالا محمود',  b'1', NOW(6) - INTERVAL 8 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(136, 'STUDENT', NOW(6), 'student06@manhaji.local', 'عمر ناصر',    b'1', NOW(6) - INTERVAL 1 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(137, 'STUDENT', NOW(6), 'student07@manhaji.local', 'سارة علي',    b'1', NOW(6) - INTERVAL 4 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(138, 'STUDENT', NOW(6), 'student08@manhaji.local', 'كريم حسن',    b'1', NOW(6) - INTERVAL 9 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(139, 'STUDENT', NOW(6), 'student09@manhaji.local', 'ريم ياسر',    b'1', NOW(6) - INTERVAL 2 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL),
(140, 'STUDENT', NOW(6), 'student10@manhaji.local', 'نور إبراهيم', b'1', NOW(6) - INTERVAL 6 DAY, '$2a$10$TqqBCKrnHGkqsdInxqrMjOqiT/N7IM/1ZfYKYsussjUxLKD.ARmuq', NULL);

INSERT INTO students (id, grade_level, avatar_id, current_streak, total_points, current_lesson_id, school_id, parent_id) VALUES
(131, 1, NULL, 3, 460, NULL, @school_id, 121),
(132, 1, NULL, 1, 320, NULL, @school_id, 121),
(133, 1, NULL, 5, 610, NULL, @school_id, 121),
(134, 1, NULL, 0, 150, NULL, @school_id, 121),
(135, 1, NULL, 2, 275, NULL, @school_id, 121),
(136, 1, NULL, 4, 530, NULL, @school_id, 121),
(137, 1, NULL, 1, 210, NULL, @school_id, 121),
(138, 1, NULL, 0,  90, NULL, @school_id, 121),
(139, 1, NULL, 2, 385, NULL, @school_id, 121),
(140, 1, NULL, 3, 440, NULL, @school_id, 121);

COMMIT;

-- Done. Next AUTO_INCREMENT for users continues above 140 automatically.

-- ============================================================================
-- VERIFICATION QUERIES (read-only — run after import)
-- ============================================================================

-- 1) All new users (expect exactly 16 rows: 101, 111-114, 121, 131-140)
-- SELECT id, role, email, full_name, is_active FROM users ORDER BY id;

-- 2) Teachers and their assigned subjects (expect 4 rows, one subject each)
-- SELECT t.id, u.email, u.full_name, s.name AS subject, ta.grade_level, ta.is_active
-- FROM teachers t
-- JOIN users u  ON u.id = t.id
-- LEFT JOIN teacher_assignments ta ON ta.teacher_id = t.id
-- LEFT JOIN subjects s ON s.id = ta.subject_id
-- ORDER BY t.id;

-- 3) No active teacher without an active assignment (must return 0 rows)
-- SELECT u.email
-- FROM teachers t
-- JOIN users u ON u.id = t.id AND u.is_active = b'1'
-- WHERE NOT EXISTS (
--   SELECT 1 FROM teacher_assignments ta
--   WHERE ta.teacher_id = t.id AND ta.is_active = b'1'
-- );

-- 4) Parent-student links (expect 10 rows, parent = parent@manhaji.local)
-- SELECT s.id, u.email AS student_email, pu.email AS parent_email, s.grade_level
-- FROM students s
-- JOIN users u  ON u.id = s.id
-- LEFT JOIN users pu ON pu.id = s.parent_id
-- ORDER BY s.id;

-- 5) Every password hash is a non-null bcrypt string (expect OK on every row)
-- SELECT id, email,
--        CASE WHEN password_hash LIKE '$2a$10$%' THEN 'OK' ELSE 'BAD' END AS hash_check
-- FROM users ORDER BY id;

-- 6) Curriculum untouched (expect: 8 / 249 / 2742 / 249 / 1)
-- SELECT 'subjects', COUNT(*) FROM subjects
-- UNION ALL SELECT 'lessons', COUNT(*) FROM lessons
-- UNION ALL SELECT 'questions', COUNT(*) FROM questions
-- UNION ALL SELECT 'quizzes', COUNT(*) FROM quizzes
-- UNION ALL SELECT 'schools', COUNT(*) FROM schools;
