"""
Backfill Grade 1 math lessons (ma1_p1.json + ma1_p2.json):

1. Add a difficulty-3 question to every math lesson that lacks one. Resolves
   R9 across all 26 math lessons.

2. Densify each lesson to ≥10 questions by adding lesson-appropriate FILL_BLANK,
   ORDERING, and (for numeral lessons) TRACING items. Resolves R8/R14.

3. Each lesson keeps its existing questions; new questions are appended.

Idempotent: questions already present (matched by `questionText`) are not re-
added. Safe to re-run.

The new questions are authored in Python literals below — keep them in sync
with the spec's per-subject template (§4.5–§4.7). Each list entry is a dict
with the same shape as a JSON question object.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CURRICULUM = (HERE.parent.parent.parent
              / "backend" / "src" / "main" / "resources" / "curriculum")

# Per-lesson additions, keyed by lesson title. Each entry is a list of question
# dicts to append (after de-duping against any existing questionText match).
# Designed so that, taken together with the lesson's existing questions, the
# lesson reaches ≥10 questions, has ≥1 difficulty-3, and covers ≥3 sub-skills.
ADDITIONS = {
    # ====================== ma1_p1 ======================
    "الأعداد ١-٥": [
        {"type": "MCQ",
         "questionText": "أي عدد بين ١ و ٣؟",
         "correctAnswer": "٢",
         "options": ["٤", "٢", "٥", "٠"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١، ٢، ___، ٤، ٥",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٣",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "handwriting"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٥",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 1, "subSkill": "handwriting"},
        {"type": "MCQ",
         "questionText": "أكبر عدد بين ١، ٤، ٢، ٣ هو؟",
         "correctAnswer": "٤",
         "options": ["١", "٢", "٣", "٤"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الأعداد ٦-٩": [
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ٦، ٧، ___، ٩",
         "correctAnswer": "٨",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "أي عدد يأتي قبل ٧ مباشرة؟",
         "correctAnswer": "٦",
         "options": ["٥", "٦", "٧", "٨"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٨",
         "correctAnswer": "٨",
         "options": None, "difficultyLevel": 1, "subSkill": "handwriting"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٩",
         "correctAnswer": "٩",
         "options": None, "difficultyLevel": 1, "subSkill": "handwriting"},
        {"type": "SHORT_ANSWER",
         "questionText": "كم عدداً بين ٥ و ٩ (لا يشمل ٥ و ٩)؟",
         "correctAnswer": "ثلاثة",
         "options": None, "difficultyLevel": 3, "subSkill": "application"},
    ],
    "العدد صفر": [
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ___، ١، ٢، ٣",
         "correctAnswer": "٠",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "٠ + ٤ = ؟",
         "correctAnswer": "٤",
         "options": ["٠", "٤", "٨", "٢"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "إذا أضفنا الصفر إلى أي عدد لا يتغير العدد",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما ناتج: ٧ ناقص ٧ ؟",
         "correctAnswer": "٠",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٠",
         "correctAnswer": "٠",
         "options": None, "difficultyLevel": 1, "subSkill": "handwriting"},
        {"type": "MCQ",
         "questionText": "هند معها ٣ تفاحات. أعطت كل واحدة لأخوتها الثلاثة. كم بقي معها؟",
         "correctAnswer": "٠",
         "options": ["٣", "١", "٠", "٢"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "مقارنة الأعداد": [
        {"type": "FILL_BLANK",
         "questionText": "ضع >  أو  <  أو  = : ٤ ___ ٤",
         "correctAnswer": "=",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "أي علامة تناسب: ٧ ___ ٣ ؟",
         "correctAnswer": ">",
         "options": [">", "<", "=", "+"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ٢ أصغر من العدد ٩",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما العدد الأصغر بين: ٦، ٤، ٨، ٢؟",
         "correctAnswer": "٢",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "إذا كان أحمد عنده ٧ كرات وعمر عنده ٤ كرات، أيهما أكثر؟",
         "correctAnswer": "أحمد",
         "options": ["أحمد", "عمر", "كلاهما متساوٍ", "لا يمكن المعرفة"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "ترتيب الأعداد": [
        {"type": "MCQ",
         "questionText": "ما العدد الذي يأتي بعد ٦ مباشرة؟",
         "correctAnswer": "٧",
         "options": ["٥", "٧", "٨", "٩"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل تنازلياً: ٩، ٨، ___، ٦، ٥",
         "correctAnswer": "٧",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "SHORT_ANSWER",
         "questionText": "اكتب العدد الذي يأتي قبل ٤ بعدد واحد",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد الذي يأتي بعد ٩ مباشرة هو ١٠",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "ORDERING",
         "questionText": "رتّب من الأكبر إلى الأصغر: ٦، ٢، ٩، ٤، ٧",
         "correctAnswer": "٩، ٧، ٦، ٤، ٢",
         "options": ["٦", "٢", "٩", "٤", "٧"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "في الترتيب التصاعدي، أي عدد يأتي ثالثاً بين: ٥، ٣، ٧، ١؟",
         "correctAnswer": "٥",
         "options": ["١", "٣", "٥", "٧"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "مكونات الأعداد": [
        {"type": "FILL_BLANK",
         "questionText": "٤ = ١ + ___",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "٦ = ٢ + ___",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ٥ يمكن تكوينه من ٢ + ٣",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ماذا نضيف إلى ٤ لنحصل على ٧؟",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "أي طريقة لا تساوي ٨؟",
         "correctAnswer": "٣ + ٤",
         "options": ["٤ + ٤", "٥ + ٣", "٦ + ٢", "٣ + ٤"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الجمع ضمن ٥": [
        {"type": "MCQ",
         "questionText": "٢ + ٣ = ؟",
         "correctAnswer": "٥",
         "options": ["٤", "٥", "٦", "٣"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١ + ___ = ٥",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: ٠ + ٥",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "٢ + ٢ يساوي ٥",
         "correctAnswer": "خطأ",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "ORDERING",
         "questionText": "رتّب نتائج الجمع تصاعدياً: ١+١، ٢+٣، ٠+٢، ٤+١",
         "correctAnswer": "٠+٢، ١+١، ٤+١، ٢+٣",
         "options": ["١+١", "٢+٣", "٠+٢", "٤+١"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الجمع ضمن ٩": [
        {"type": "MCQ",
         "questionText": "٤ + ٤ = ؟",
         "correctAnswer": "٨",
         "options": ["٧", "٨", "٩", "٦"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "٥ + ___ = ٩",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "٣ + ٦ = ٩",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "إذا كان معك ٤ تفاحات وأعطاك أبوك ٣ تفاحات، كم أصبح المجموع؟",
         "correctAnswer": "٧",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "هند جمعت ٢ + ٣ ثم أضافت ٤. ما الناتج؟",
         "correctAnswer": "٩",
         "options": ["٧", "٨", "٩", "١٠"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الطرح ضمن ٥": [
        {"type": "MCQ",
         "questionText": "٥ - ٢ = ؟",
         "correctAnswer": "٣",
         "options": ["١", "٢", "٣", "٤"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ٤ - ___ = ١",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "٥ - ٥ = ٠",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: ٣ - ٠",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "كان عند سامي ٥ بالونات، انفجر ٢ منها. كم بقي؟",
         "correctAnswer": "٣",
         "options": ["٢", "٣", "٤", "٥"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الطرح ضمن ٩": [
        {"type": "MCQ",
         "questionText": "٩ - ٤ = ؟",
         "correctAnswer": "٥",
         "options": ["٣", "٤", "٥", "٦"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "٨ - ___ = ٣",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "٧ - ٠ = ٧",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: ٩ - ٩",
         "correctAnswer": "٠",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "في صف فيه ٩ طلاب، غاب ٣ منهم. كم طالباً حضر؟",
         "correctAnswer": "٦",
         "options": ["٥", "٦", "٧", "٨"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "مراجعة الجمع والطرح": [
        {"type": "MCQ",
         "questionText": "٦ + ٣ = ؟",
         "correctAnswer": "٩",
         "options": ["٧", "٨", "٩", "١٠"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "٩ - ٢ = ؟",
         "correctAnswer": "٧",
         "options": ["٦", "٧", "٨", "٩"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ٤ + ___ = ٧",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "ناتج ٣ + ٤ يساوي ناتج ٩ - ٢",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: (٢ + ٣) - ١",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "ليلى عندها ٨ زهور، أخذت أمها ٣ ثم أعطتها ٢ أخرى. كم أصبح عندها؟",
         "correctAnswer": "٧",
         "options": ["٥", "٦", "٧", "٨"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "العدد ١٠": [
        {"type": "MCQ",
         "questionText": "كم وحدة في العدد ١٠؟",
         "correctAnswer": "صفر وحدة وعشرة آحاد",
         "options": ["وحدة واحدة فقط", "صفر وحدة وعشرة آحاد", "عشر آحاد وعشر عشرات", "خمس وحدات"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ١٠ يأتي بعد ٩ مباشرة",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما ناتج: ٥ + ٥ ؟",
         "correctAnswer": "١٠",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٠ - ___ = ٤",
         "correctAnswer": "٦",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ١٠",
         "correctAnswer": "١٠",
         "options": None, "difficultyLevel": 2, "subSkill": "handwriting"},
        {"type": "MCQ",
         "questionText": "أي مما يلي يساوي ١٠؟",
         "correctAnswer": "٧ + ٣",
         "options": ["٨ + ١", "٧ + ٣", "٦ + ٣", "٥ + ٤"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الأعداد ١١-١٥": [
        {"type": "MCQ",
         "questionText": "أي عدد يأتي بين ١٢ و ١٤؟",
         "correctAnswer": "١٣",
         "options": ["١١", "١٢", "١٣", "١٥"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١١، ١٢، ١٣، ___، ١٥",
         "correctAnswer": "١٤",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ١٣ مكون من ١ عشرة و ٣ آحاد",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "كم آحاداً في العدد ١٥؟",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ١٢",
         "correctAnswer": "١٢",
         "options": None, "difficultyLevel": 2, "subSkill": "handwriting"},
        {"type": "MCQ",
         "questionText": "أيهما أكبر: ١٣ أم ١٤ بعدد كم؟",
         "correctAnswer": "١٤ أكبر بـ ١",
         "options": ["متساويان", "١٣ أكبر بـ ١", "١٤ أكبر بـ ١", "١٤ أكبر بـ ٢"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الأعداد ١٦-٢٠": [
        {"type": "MCQ",
         "questionText": "ما العدد الذي يأتي بعد ١٩؟",
         "correctAnswer": "٢٠",
         "options": ["١٨", "٢٠", "٢١", "١٧"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٧، ١٨، ___، ٢٠",
         "correctAnswer": "١٩",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ٢٠ يساوي عشرتين",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "كم عشرة في العدد ١٨؟",
         "correctAnswer": "١",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRACING",
         "questionText": "اكتب الرقم ٢٠",
         "correctAnswer": "٢٠",
         "options": None, "difficultyLevel": 2, "subSkill": "handwriting"},
        {"type": "MCQ",
         "questionText": "إذا أضفنا ٤ إلى ١٦ فما الناتج؟",
         "correctAnswer": "٢٠",
         "options": ["١٨", "١٩", "٢٠", "٢١"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "مراجعة شاملة": [
        {"type": "MCQ",
         "questionText": "ما ناتج ٧ + ٣؟",
         "correctAnswer": "١٠",
         "options": ["٩", "١٠", "١١", "١٢"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ١٥ أصغر من العدد ٢٠",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٤ - ___ = ١٠",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما العدد الذي يأتي بين ١٧ و ١٩؟",
         "correctAnswer": "١٨",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "ORDERING",
         "questionText": "رتّب تصاعدياً: ١٢، ٧، ٢٠، ١٥، ٩",
         "correctAnswer": "٧، ٩، ١٢، ١٥، ٢٠",
         "options": ["١٢", "٧", "٢٠", "١٥", "٩"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "اشترى عمر ٦ أقلام ووالده اشترى ٤ أقلام أخرى. كم قلماً معهما الآن؟",
         "correctAnswer": "١٠",
         "options": ["٨", "٩", "١٠", "١١"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],

    # ====================== ma1_p2 ======================
    "الجمع ضمن ٢٠": [
        {"type": "MCQ",
         "questionText": "١٠ + ٥ = ؟",
         "correctAnswer": "١٥",
         "options": ["١٤", "١٥", "١٦", "٢٠"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "٨ + ٧ = ؟",
         "correctAnswer": "١٥",
         "options": ["١٤", "١٥", "١٦", "١٧"],
         "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٢ + ___ = ٢٠",
         "correctAnswer": "٨",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "٩ + ٩ = ١٨",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: ٦ + ٧",
         "correctAnswer": "١٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "ORDERING",
         "questionText": "رتّب نتائج الجمع تصاعدياً: ٤+٤، ١٠+٥، ٧+٢، ٩+٣",
         "correctAnswer": "٧+٢، ٤+٤، ٩+٣، ١٠+٥",
         "options": ["٤+٤", "١٠+٥", "٧+٢", "٩+٣"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الطرح ضمن ٢٠": [
        {"type": "MCQ",
         "questionText": "١٧ - ٥ = ؟",
         "correctAnswer": "١٢",
         "options": ["١٠", "١١", "١٢", "١٣"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "٢٠ - ٧ = ؟",
         "correctAnswer": "١٣",
         "options": ["١١", "١٢", "١٣", "١٤"],
         "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٤ - ___ = ٦",
         "correctAnswer": "٨",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "١٨ - ٩ = ٩",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "احسب: ١٥ - ٠",
         "correctAnswer": "١٥",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "كان مع ريم ٢٠ ريالاً، اشترت لعبة بـ ٧ ريالات وكتاباً بـ ٥. كم بقي؟",
         "correctAnswer": "٨",
         "options": ["٦", "٧", "٨", "٩"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "حقائق الجمع والطرح": [
        {"type": "MCQ",
         "questionText": "إذا كان ٣ + ٤ = ٧، فإن ٧ - ٤ = ؟",
         "correctAnswer": "٣",
         "options": ["٢", "٣", "٤", "٥"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "FILL_BLANK",
         "questionText": "إذا كان ٦ + ٢ = ٨، فإن ٨ - ٦ = ___",
         "correctAnswer": "٢",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "الجمع والطرح عمليتان متعاكستان",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "أكمل: ٩ - ٤ = ٥. إذن ٤ + ٥ = ؟",
         "correctAnswer": "٩",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "أي حقيقة جمع تقابل ١٠ - ٦ = ٤؟",
         "correctAnswer": "٦ + ٤ = ١٠",
         "options": ["٤ + ٤ = ٨", "٦ + ٤ = ١٠", "٥ + ٥ = ١٠", "٦ + ٦ = ١٢"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب الأسرة الحسابية للعدد ٥: ٢+٣، ٥-٢، ٣+٢، ٥-٣",
         "correctAnswer": "٢+٣، ٣+٢، ٥-٢، ٥-٣",
         "options": ["٢+٣", "٥-٢", "٣+٢", "٥-٣"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الأشكال الهندسية": [
        {"type": "MCQ",
         "questionText": "كم ضلعاً للمثلث؟",
         "correctAnswer": "٣",
         "options": ["٢", "٣", "٤", "٥"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "للمربع أربعة أضلاع متساوية",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما اسم الشكل الذي ليس له أضلاع؟",
         "correctAnswer": "الدائرة",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: المستطيل له ___ أضلاع",
         "correctAnswer": "٤",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "أي شكل يشبه عجلة السيارة؟",
         "correctAnswer": "الدائرة",
         "options": ["المربع", "المثلث", "الدائرة", "المستطيل"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "إذا قطعنا المربع إلى نصفين متساويين بخط مستقيم، نحصل على شكلين من نوع:",
         "correctAnswer": "مستطيل",
         "options": ["مربع", "مستطيل", "مثلث", "دائرة"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب الأشكال حسب عدد الأضلاع تصاعدياً: مربع، مثلث، دائرة، خماسي",
         "correctAnswer": "دائرة، مثلث، مربع، خماسي",
         "options": ["مربع", "مثلث", "دائرة", "خماسي"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "الأنماط": [
        {"type": "MCQ",
         "questionText": "ما الشكل التالي في النمط: 🔴🔵🔴🔵🔴__؟",
         "correctAnswer": "🔵",
         "options": ["🔴", "🔵", "🟡", "🟢"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل النمط: ٢، ٤، ٦، ___، ١٠",
         "correctAnswer": "٨",
         "options": None, "difficultyLevel": 2, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "النمط ١، ٣، ٥، ٧ هو نمط الأعداد الفردية",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "أكمل النمط: ١، ٢، ١، ٢، ١، ___",
         "correctAnswer": "٢",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "ما الناتج في النمط: ٥، ١٠، ١٥، ٢٠، ___؟",
         "correctAnswer": "٢٥",
         "options": ["٢٠", "٢٢", "٢٥", "٣٠"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب الأعداد لتكوين نمط الأعداد الزوجية: ٦، ٢، ٤، ٨",
         "correctAnswer": "٢، ٤، ٦، ٨",
         "options": ["٦", "٢", "٤", "٨"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: △◯△◯△___",
         "correctAnswer": "◯",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
    ],
    "القياس والطول": [
        {"type": "MCQ",
         "questionText": "أي وحدة نستخدمها لقياس الطول الكبير كطول الغرفة؟",
         "correctAnswer": "المتر",
         "options": ["السنتيمتر", "المتر", "الكيلومتر", "الجرام"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "السنتيمتر أصغر من المتر",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما الأداة التي نستخدمها لقياس الطول؟",
         "correctAnswer": "المسطرة",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: لقياس طول قلم نستخدم ___",
         "correctAnswer": "السنتيمتر",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "إذا كان طول كتاب ٢٠ سم وطول قلم ١٢ سم، فالكتاب أطول من القلم بـ:",
         "correctAnswer": "٨ سم",
         "options": ["٦ سم", "٧ سم", "٨ سم", "١٠ سم"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب من الأقصر إلى الأطول: قلم، كتاب، طاولة، باب",
         "correctAnswer": "قلم، كتاب، طاولة، باب",
         "options": ["كتاب", "قلم", "باب", "طاولة"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "المتر يساوي ١٠٠ سنتيمتر",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "الوزن والسعة": [
        {"type": "MCQ",
         "questionText": "أيهما أثقل عادةً: تفاحة أم بطيخة؟",
         "correctAnswer": "بطيخة",
         "options": ["تفاحة", "بطيخة", "كلاهما متساوٍ", "لا يمكن المقارنة"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "نقيس الوزن بالميزان",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما الأداة التي نستخدمها لقياس السعة؟",
         "correctAnswer": "كأس القياس",
         "options": None, "difficultyLevel": 2, "subSkill": "production"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: نقيس الوزن بـ ___",
         "correctAnswer": "الميزان",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "أي إناء يستوعب ماءً أكثر: كأس صغير أم إبريق كبير؟",
         "correctAnswer": "إبريق كبير",
         "options": ["كأس صغير", "إبريق كبير", "متساويان", "الكأس فقط"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "ORDERING",
         "questionText": "رتّب من الأخف إلى الأثقل: قطة، فيل، طائر، كلب",
         "correctAnswer": "طائر، قطة، كلب، فيل",
         "options": ["قطة", "فيل", "طائر", "كلب"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "حبة الأرز أثقل من البرتقالة",
         "correctAnswer": "خطأ",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
    ],
    "الوقت والساعة": [
        {"type": "MCQ",
         "questionText": "كم ساعة في اليوم؟",
         "correctAnswer": "٢٤",
         "options": ["١٢", "٢٤", "٦٠", "٧"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "الساعة فيها عقربان: عقرب الساعات وعقرب الدقائق",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "كم دقيقة في الساعة الواحدة؟",
         "correctAnswer": "٦٠",
         "options": None, "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: عقرب الساعات أقصر من عقرب ___",
         "correctAnswer": "الدقائق",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "إذا كانت الساعة الآن ٣ وبعد ساعتين، كم ستكون؟",
         "correctAnswer": "٥",
         "options": ["٤", "٥", "٦", "٧"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب أوقات اليوم بالترتيب: ظهراً، صباحاً، ليلاً، مساءً",
         "correctAnswer": "صباحاً، ظهراً، مساءً، ليلاً",
         "options": ["ظهراً", "صباحاً", "ليلاً", "مساءً"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "نوم الأطفال يكون عادة في الليل",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
    ],
    "النقود": [
        {"type": "MCQ",
         "questionText": "كم قرشاً في الشيكل الواحد؟",
         "correctAnswer": "١٠٠",
         "options": ["١٠", "٥٠", "١٠٠", "١٠٠٠"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "نستخدم النقود لشراء الأشياء",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "إذا كان معك ٥ شواكل واشتريت بسكويتاً بـ ٢ شواكل، كم بقي؟",
         "correctAnswer": "٣",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ٢ شيكل + ٣ شيكل = ___ شيكل",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "اشترى أحمد لعبة بـ ١٠ شواكل ودفتراً بـ ٤ شواكل. كم دفع؟",
         "correctAnswer": "١٤",
         "options": ["١٣", "١٤", "١٥", "١٦"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "أعطى الأب ابنه ٢٠ شيكلاً، فاشترى الابن قميصاً بـ ١٢ شيكلاً وحلوى بـ ٣ شواكل. كم بقي معه؟",
         "correctAnswer": "٥",
         "options": ["٤", "٥", "٦", "٧"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب الفئات النقدية تصاعدياً: ٥ شيكل، شيكل، ٢٠ شيكل، ١٠ شيكل",
         "correctAnswer": "شيكل، ٥ شيكل، ١٠ شيكل، ٢٠ شيكل",
         "options": ["٥ شيكل", "شيكل", "٢٠ شيكل", "١٠ شيكل"],
         "difficultyLevel": 2, "subSkill": "application"},
    ],
    "مسائل كلامية": [
        {"type": "MCQ",
         "questionText": "في حديقة ٧ زهور حمراء و٥ زهور صفراء. كم زهرة في الحديقة؟",
         "correctAnswer": "١٢",
         "options": ["١٠", "١١", "١٢", "١٣"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "SHORT_ANSWER",
         "questionText": "كان عندي ١٥ كرة، أعطيت أخي ٦ كرات. كم بقي عندي؟",
         "correctAnswer": "٩",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
        {"type": "TRUE_FALSE",
         "questionText": "إذا قرأ سامي ٤ صفحات في اليوم الأول و٥ صفحات في اليوم الثاني، فقد قرأ ٩ صفحات",
         "correctAnswer": "صح",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: عند ليلى ١٠ تفاحات. أعطت أخاها ٤ تفاحات. بقي عندها ___ تفاحات",
         "correctAnswer": "٦",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "في مزرعة ٨ دجاجات و٤ ديوك. كم طيراً في المزرعة؟",
         "correctAnswer": "١٢",
         "options": ["١١", "١٢", "١٣", "١٤"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "اشترت أمي ٦ بيضات صباحاً و٧ بيضات مساءً. ثم استعملت ٤ بيضات في الطبخ. كم بقي؟",
         "correctAnswer": "٩",
         "options": ["٧", "٨", "٩", "١٠"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER",
         "questionText": "في الصف ١٢ ولداً و٨ بنات. كم طالباً في الصف؟",
         "correctAnswer": "٢٠",
         "options": None, "difficultyLevel": 1, "subSkill": "application"},
    ],
    "مراجعة نهائية": [
        {"type": "MCQ",
         "questionText": "ما ناتج: ١٠ + ٦؟",
         "correctAnswer": "١٦",
         "options": ["١٤", "١٥", "١٦", "١٧"],
         "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "TRUE_FALSE",
         "questionText": "العدد ١٣ أكبر من العدد ١٧",
         "correctAnswer": "خطأ",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "أكمل: ١٧ - ___ = ١٢",
         "correctAnswer": "٥",
         "options": None, "difficultyLevel": 2, "subSkill": "computation"},
        {"type": "SHORT_ANSWER",
         "questionText": "ما اسم الشكل الذي له ٣ أضلاع؟",
         "correctAnswer": "المثلث",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "كم متراً تقريباً يبلغ ارتفاع الباب العادي؟",
         "correctAnswer": "٢ متر",
         "options": ["٢٠ سم", "٥٠ سم", "٢ متر", "١٠ أمتار"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "رتّب تنازلياً: ٨، ١٤، ٢، ١٩، ١١",
         "correctAnswer": "١٩، ١٤، ١١، ٨، ٢",
         "options": ["٨", "١٤", "٢", "١٩", "١١"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "مزرعة فيها ١٠ خراف. ولدت ٣ منها صغاراً، وبيع ٢ منها. كم خروفاً بقي في المزرعة؟",
         "correctAnswer": "١١",
         "options": ["٩", "١٠", "١١", "١٢"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
}


def main():
    files = ["ma1_p1.json", "ma1_p2.json"]
    grand_added = 0
    for fname in files:
        path = CURRICULUM / fname
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        added_in_file = 0
        for lesson in data.get("lessons", []):
            title = lesson.get("title")
            if title not in ADDITIONS:
                continue
            existing_text = {q.get("questionText") for q in lesson.get("questions", [])}
            for new_q in ADDITIONS[title]:
                if new_q["questionText"] in existing_text:
                    continue  # idempotent
                lesson["questions"].append(new_q)
                added_in_file += 1
        if added_in_file > 0:
            with path.open("w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write("\n")
        print(f"  {fname}: added {added_in_file} questions")
        grand_added += added_in_file
    print(f"DONE: added {grand_added} math questions across {len(files)} files.")


if __name__ == "__main__":
    main()
