"""
Backfill Grade 1 Religion lessons (re1_p1.json + re1_p2.json):

For each of the 26 lessons add 5-8 questions:
- Surah lessons gain PRONUNCIATION (recitation) + ORDERING (ayah ordering) +
  difficulty-3 (full ayah completion).
- Procedural lessons (Wudu, Salah) gain mandatory ORDERING (step sequence)
  per spec §4.9.
- Story / Adab lessons gain ORDERING (story sequencing) + difficulty-3.

Idempotent.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
CURRICULUM = HERE.parent.parent.parent / "backend" / "src" / "main" / "resources" / "curriculum"

ADDITIONS = {
    # ===== re1_p1 =====
    "الله ربي": [
        {"type": "MCQ", "questionText": "من الذي خلق الإنسان؟",
         "correctAnswer": "الله", "options": ["الإنسان", "الحيوان", "الله", "النبات"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: ___ هو ربي وربكم",
         "correctAnswer": "الله", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "الله تعالى لا يشبه أحداً من مخلوقاته",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: الحمد لله رب العالمين",
         "correctAnswer": "الحمد لله رب العالمين", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب الكلمات: العالمين، الحمد، رب، لله",
         "correctAnswer": "الحمد، لله، رب، العالمين",
         "options": ["العالمين", "الحمد", "رب", "لله"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "أي مما يلي ليس من نعم الله؟",
         "correctAnswer": "الكذب",
         "options": ["السمع", "البصر", "الكذب", "العقل"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر نعمة من نعم الله",
         "correctAnswer": "السمع", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "أركان الإسلام": [
        {"type": "MCQ", "questionText": "ما الركن الذي نصومه في رمضان؟",
         "correctAnswer": "الصوم", "options": ["الصلاة", "الزكاة", "الصوم", "الحج"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: الحج إلى بيت الله ___",
         "correctAnswer": "الحرام", "options": None,
         "difficultyLevel": 2, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "الزكاة ركن من أركان الإسلام",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل الشهادتين: أشهد أن لا إله إلا الله، وأشهد أن محمداً رسول الله",
         "correctAnswer": "أشهد أن لا إله إلا الله وأشهد أن محمداً رسول الله",
         "options": None, "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب أركان الإسلام: الصلاة، الشهادتان، الحج، الزكاة، الصوم",
         "correctAnswer": "الشهادتان، الصلاة، الزكاة، الصوم، الحج",
         "options": ["الصلاة", "الشهادتان", "الحج", "الزكاة", "الصوم"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "ما ركن الإسلام الخاص بالأموال؟",
         "correctAnswer": "الزكاة", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "سورة الفاتحة": [
        {"type": "MCQ", "questionText": "من رب العالمين؟",
         "correctAnswer": "الله", "options": ["الإنسان", "الله", "الملك", "الشمس"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: الحمد لله رب العالمين",
         "correctAnswer": "الحمد لله رب العالمين", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: الرحمن الرحيم",
         "correctAnswer": "الرحمن الرحيم", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: مالك يوم الدين",
         "correctAnswer": "مالك يوم الدين", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "SHORT_ANSWER", "questionText": "أكمل: إياك نعبد وإياك ...",
         "correctAnswer": "نستعين", "options": None,
         "difficultyLevel": 2, "subSkill": "memorization"},
        {"type": "ORDERING", "questionText": "رتّب آيات أول الفاتحة: الرحمن الرحيم، الحمد لله رب العالمين، بسم الله الرحمن الرحيم، مالك يوم الدين",
         "correctAnswer": "بسم الله الرحمن الرحيم، الحمد لله رب العالمين، الرحمن الرحيم، مالك يوم الدين",
         "options": ["الرحمن الرحيم", "الحمد لله رب العالمين", "بسم الله الرحمن الرحيم", "مالك يوم الدين"],
         "difficultyLevel": 3, "subSkill": "memorization"},
        {"type": "MCQ", "questionText": "كم عدد آيات سورة الفاتحة؟",
         "correctAnswer": "سبع", "options": ["خمس", "ست", "سبع", "عشر"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "سورة الإخلاص": [
        {"type": "PRONUNCIATION", "questionText": "اقرأ: قل هو الله أحد",
         "correctAnswer": "قل هو الله أحد", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: الله الصمد",
         "correctAnswer": "الله الصمد", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: لم يلد ولم يولد",
         "correctAnswer": "لم يلد ولم يولد", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "SHORT_ANSWER", "questionText": "أكمل: ولم يكن له كفواً ...",
         "correctAnswer": "أحد", "options": None,
         "difficultyLevel": 2, "subSkill": "memorization"},
        {"type": "ORDERING", "questionText": "رتّب آيات سورة الإخلاص: الله الصمد، قل هو الله أحد، ولم يكن له كفواً أحد، لم يلد ولم يولد",
         "correctAnswer": "قل هو الله أحد، الله الصمد، لم يلد ولم يولد، ولم يكن له كفواً أحد",
         "options": ["الله الصمد", "قل هو الله أحد", "ولم يكن له كفواً أحد", "لم يلد ولم يولد"],
         "difficultyLevel": 3, "subSkill": "memorization"},
        {"type": "MCQ", "questionText": "كم عدد آيات سورة الإخلاص؟",
         "correctAnswer": "أربع", "options": ["ثلاث", "أربع", "خمس", "ست"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "MCQ", "questionText": "ماذا تعلمنا سورة الإخلاص عن الله؟",
         "correctAnswer": "أنه واحد لا شريك له",
         "options": ["أنه يأكل ويشرب", "أنه واحد لا شريك له", "أن له والداً", "أن له شبيهاً"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "نعم الله تعالى": [
        {"type": "MCQ", "questionText": "أي مما يلي نعمة من نعم الله؟",
         "correctAnswer": "الصحة", "options": ["المرض", "الكذب", "الصحة", "الكسل"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: نقول ___ لله بعد كل نعمة",
         "correctAnswer": "الحمد", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نعم الله علينا لا تعد ولا تحصى",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: الحمد لله على نعمه",
         "correctAnswer": "الحمد لله على نعمه", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب نعم الحواس: السمع، البصر، الشم، الذوق",
         "correctAnswer": "البصر، السمع، الشم، الذوق",
         "options": ["السمع", "البصر", "الشم", "الذوق"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "كيف نشكر الله على نعمه؟",
         "correctAnswer": "بطاعته وذكره وحمده",
         "options": ["بنسيانها", "بالتذمر", "بطاعته وذكره وحمده", "بإخفائها"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر نعمة من نعم الله في جسمك",
         "correctAnswer": "البصر", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "رسولنا محمد ﷺ": [
        {"type": "MCQ", "questionText": "في أي مدينة وُلد النبي محمد ﷺ؟",
         "correctAnswer": "مكة", "options": ["المدينة", "مكة", "القدس", "بغداد"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: محمد بن ___ بن عبد المطلب",
         "correctAnswer": "عبدالله", "options": None,
         "difficultyLevel": 2, "subSkill": "memorization"},
        {"type": "TRUE_FALSE", "questionText": "ولد النبي محمد ﷺ في عام الفيل",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: اللهم صلِّ على محمد",
         "correctAnswer": "اللهم صل على محمد", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب أحداث حياة النبي ﷺ: الهجرة، البعثة، الولادة، الوفاة",
         "correctAnswer": "الولادة، البعثة، الهجرة، الوفاة",
         "options": ["الهجرة", "البعثة", "الولادة", "الوفاة"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "اسم أم النبي ﷺ:",
         "correctAnswer": "آمنة", "options": ["خديجة", "آمنة", "عائشة", "فاطمة"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER", "questionText": "ما اسم جد النبي ﷺ الذي ربّاه؟",
         "correctAnswer": "عبد المطلب", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "صفات الرسول ﷺ": [
        {"type": "MCQ", "questionText": "اشتُهر النبي ﷺ قبل النبوة بصفة:",
         "correctAnswer": "الصدق والأمانة",
         "options": ["الكذب", "الصدق والأمانة", "الكسل", "الغضب"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: لُقّب النبي ﷺ بالصادق ___",
         "correctAnswer": "الأمين", "options": None,
         "difficultyLevel": 1, "subSkill": "memorization"},
        {"type": "TRUE_FALSE", "questionText": "كان النبي ﷺ يبتسم ويرحم الصغار",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: صلى الله عليه وسلم",
         "correctAnswer": "صلى الله عليه وسلم", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب الصفات حسب الفضل في الإسلام: الكذب، الصدق، الخيانة، الأمانة",
         "correctAnswer": "الصدق، الأمانة، الكذب، الخيانة",
         "options": ["الكذب", "الصدق", "الخيانة", "الأمانة"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "أي تصرف لا يليق بأخلاق النبي ﷺ؟",
         "correctAnswer": "الكذب على الناس",
         "options": ["الصدق", "الرحمة", "الكذب على الناس", "الأمانة"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر صفة من صفات النبي ﷺ غير الصدق",
         "correctAnswer": "الأمانة", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "أحب رسولي ﷺ": [
        {"type": "MCQ", "questionText": "كيف نُظهر حبنا للنبي ﷺ؟",
         "correctAnswer": "باتباع سنته",
         "options": ["بنسيانه", "باتباع سنته", "بمخالفته", "بالسكوت عنه"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK", "questionText": "أكمل: من أحبني فلا يكذب على ___",
         "correctAnswer": "أحد", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "حب النبي ﷺ من أعظم الإيمان",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: اللهم صلِّ وسلِّم على نبينا محمد",
         "correctAnswer": "اللهم صل وسلم على نبينا محمد", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب طرق إظهار الحب: السلام عليه، اتباع سنته، الصلاة عليه",
         "correctAnswer": "الصلاة عليه، السلام عليه، اتباع سنته",
         "options": ["السلام عليه", "اتباع سنته", "الصلاة عليه"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "أيهما يُظهر حب النبي ﷺ أكثر؟",
         "correctAnswer": "تطبيق أخلاقه في حياتنا",
         "options": ["كتابة اسمه فقط", "ذكره مرة واحدة", "تطبيق أخلاقه في حياتنا", "تعليقه على الجدار"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "ماذا نقول إذا ذُكر النبي ﷺ؟",
         "correctAnswer": "صلى الله عليه وسلم", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "الصدق": [
        {"type": "MCQ", "questionText": "الصادق يحبه:",
         "correctAnswer": "الله والناس", "options": ["لا أحد", "الله فقط", "الناس فقط", "الله والناس"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: الصدق طريق إلى ___",
         "correctAnswer": "الجنة", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "يجب أن نصدق دائماً ولو في المزاح",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: الصدق منجاة",
         "correctAnswer": "الصدق منجاة", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب نتائج الصدق: محبة الناس، حب الله، دخول الجنة",
         "correctAnswer": "حب الله، محبة الناس، دخول الجنة",
         "options": ["محبة الناس", "حب الله", "دخول الجنة"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "كسر زيد كأساً فقالت له أمه: من كسره؟ ماذا يفعل الصادق؟",
         "correctAnswer": "يقول: أنا كسرته يا أمي",
         "options": ["يصمت ولا يجيب", "يقول: لا أعرف", "يلوم أخاه", "يقول: أنا كسرته يا أمي"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "ما عكس الصدق؟",
         "correctAnswer": "الكذب", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "الأمانة": [
        {"type": "MCQ", "questionText": "الأمانة تعني:",
         "correctAnswer": "ردّ الحقوق إلى أصحابها",
         "options": ["أخذ ما ليس لك", "ردّ الحقوق إلى أصحابها", "النوم", "اللعب"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: من علامات الإيمان حفظ ___",
         "correctAnswer": "الأمانة", "options": None,
         "difficultyLevel": 2, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "إذا أعطاك صديقك قلماً ليوم واحد، يجب إرجاعه",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "PRONUNCIATION", "questionText": "قل: الأمين محبوب",
         "correctAnswer": "الأمين محبوب", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب درجات الأمانة: حفظ الأسرار، حفظ الأشياء، أداء الحقوق",
         "correctAnswer": "حفظ الأشياء، حفظ الأسرار، أداء الحقوق",
         "options": ["حفظ الأسرار", "حفظ الأشياء", "أداء الحقوق"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "وجدت محفظة بها مال على الطريق. الأمانة تقتضي:",
         "correctAnswer": "البحث عن صاحبها وإعادتها",
         "options": ["أخذ المال لنفسي", "تركها", "إخبار صاحبها فقط", "البحث عن صاحبها وإعادتها"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "بماذا لُقّب النبي ﷺ بسبب أمانته؟",
         "correctAnswer": "الأمين", "options": None,
         "difficultyLevel": 1, "subSkill": "memorization"},
    ],
    "احترام الكبير": [
        {"type": "MCQ", "questionText": "كيف نتحدث مع الكبير؟",
         "correctAnswer": "بصوت لطيف وأدب",
         "options": ["بصوت عالٍ", "بكلمات سيئة", "بصوت لطيف وأدب", "لا نتحدث"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK", "questionText": "أكمل: من احترام الكبير عدم رفع ___ في حضرته",
         "correctAnswer": "الصوت", "options": None,
         "difficultyLevel": 2, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نقف للكبير ونساعده على الجلوس",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "PRONUNCIATION", "questionText": "قل: السلام عليكم ورحمة الله وبركاته",
         "correctAnswer": "السلام عليكم ورحمة الله وبركاته", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب آداب لقاء الكبير: السلام، الجلوس بأدب، الوقوف، التحية باليد",
         "correctAnswer": "الوقوف، السلام، التحية باليد، الجلوس بأدب",
         "options": ["السلام", "الجلوس بأدب", "الوقوف", "التحية باليد"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "في الباص لا يوجد مقعد فارغ. دخل رجل كبير في السن. ماذا تفعل؟",
         "correctAnswer": "أقوم وأعطيه مقعدي",
         "options": ["أتظاهر بالنوم", "أتجاهله", "أقوم وأعطيه مقعدي", "أنادي شخصاً آخر"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر طريقة لاحترام والديك",
         "correctAnswer": "أطيعهما", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "الوضوء": [
        {"type": "MCQ", "questionText": "بماذا نبدأ الوضوء؟",
         "correctAnswer": "بالتسمية", "options": ["بغسل اليدين", "بالتسمية", "بمسح الرأس", "بغسل الرجلين"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: نغسل الوجه ___ مرات",
         "correctAnswer": "ثلاث", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "نمسح الرأس مرة واحدة في الوضوء",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: بسم الله",
         "correctAnswer": "بسم الله", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب خطوات الوضوء: غسل الوجه، غسل اليدين إلى المرفقين، التسمية، غسل الكفين، مسح الرأس، غسل الرجلين",
         "correctAnswer": "التسمية، غسل الكفين، غسل الوجه، غسل اليدين إلى المرفقين، مسح الرأس، غسل الرجلين",
         "options": ["غسل الوجه", "غسل اليدين إلى المرفقين", "التسمية", "غسل الكفين", "مسح الرأس", "غسل الرجلين"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING", "questionText": "رتّب أعضاء الوضوء من الأعلى إلى الأسفل: الوجه، الرأس، الرجلين، اليدين",
         "correctAnswer": "الرأس، الوجه، اليدين، الرجلين",
         "options": ["الوجه", "الرأس", "الرجلين", "اليدين"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "كم مرة نغسل اليدين في الوضوء؟",
         "correctAnswer": "ثلاث", "options": ["مرة", "مرتان", "ثلاث", "أربع"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
    ],
    "الصلاة": [
        {"type": "MCQ", "questionText": "ما الصلاة الأولى في اليوم؟",
         "correctAnswer": "الفجر", "options": ["الظهر", "العصر", "الفجر", "العشاء"],
         "difficultyLevel": 1, "subSkill": "memorization"},
        {"type": "FILL_BLANK", "questionText": "أكمل: عدد الصلوات اليومية ___",
         "correctAnswer": "خمس", "options": None,
         "difficultyLevel": 1, "subSkill": "memorization"},
        {"type": "TRUE_FALSE", "questionText": "صلاة المغرب بعد صلاة العصر",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: الله أكبر",
         "correctAnswer": "الله أكبر", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب الصلوات الخمس بترتيبها اليومي: العصر، الفجر، العشاء، المغرب، الظهر",
         "correctAnswer": "الفجر، الظهر، العصر، المغرب، العشاء",
         "options": ["العصر", "الفجر", "العشاء", "المغرب", "الظهر"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING", "questionText": "رتّب أركان الركعة الأساسية: السجود، الركوع، القراءة، التكبير",
         "correctAnswer": "التكبير، القراءة، الركوع، السجود",
         "options": ["السجود", "الركوع", "القراءة", "التكبير"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "كم ركعة في صلاة الفجر؟",
         "correctAnswer": "ركعتان", "options": ["ركعة", "ركعتان", "ثلاث", "أربع"],
         "difficultyLevel": 2, "subSkill": "memorization"},
    ],
    "آداب المسجد": [
        {"type": "MCQ", "questionText": "بأي قدم ندخل المسجد؟",
         "correctAnswer": "اليمنى", "options": ["اليسرى", "اليمنى", "كلتاهما", "بدون أحذية فقط"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: نحافظ على ___ المسجد",
         "correctAnswer": "نظافة", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نتحدث بصوت عالٍ في المسجد",
         "correctAnswer": "خطأ", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل عند دخول المسجد: اللهم افتح لي أبواب رحمتك",
         "correctAnswer": "اللهم افتح لي أبواب رحمتك", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب آداب الدخول: قول الدعاء، الدخول بالقدم اليمنى، خلع الحذاء، الجلوس بأدب",
         "correctAnswer": "خلع الحذاء، الدخول بالقدم اليمنى، قول الدعاء، الجلوس بأدب",
         "options": ["قول الدعاء", "الدخول بالقدم اليمنى", "خلع الحذاء", "الجلوس بأدب"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "ماذا نفعل إذا رأينا قمامة في المسجد؟",
         "correctAnswer": "نرفعها ونضعها في سلة المهملات",
         "options": ["نتركها", "نمشي عليها", "نرفعها ونضعها في سلة المهملات", "نشتكي للمسؤول فقط"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "ما اسم البيت الذي نصلي فيه جماعة؟",
         "correctAnswer": "المسجد", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "مراجعة عامة": [  # re1_p1 review (orderIndex 15)
        {"type": "FILL_BLANK", "questionText": "أكمل: الصلاة عمود ___",
         "correctAnswer": "الدين", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: لا إله إلا الله",
         "correctAnswer": "لا إله إلا الله", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب من الأول إلى الأخير: قراءة الفاتحة، التكبير، السجود، الركوع",
         "correctAnswer": "التكبير، قراءة الفاتحة، الركوع، السجود",
         "options": ["قراءة الفاتحة", "التكبير", "السجود", "الركوع"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "ما الذي يجب أن نفعله قبل الصلاة؟",
         "correctAnswer": "الوضوء", "options": ["الأكل", "النوم", "الوضوء", "اللعب"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "حب النبي ﷺ من علامات الإيمان",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "MCQ", "questionText": "أي مما يلي ركن من أركان الإسلام؟",
         "correctAnswer": "الحج",
         "options": ["النوم المبكر", "الحج", "الرياضة", "السفر"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER", "questionText": "ما اسم المكان الذي يصلي فيه المسلمون جماعة؟",
         "correctAnswer": "المسجد", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],

    # ===== re1_p2 =====
    "سورة الناس": [
        {"type": "PRONUNCIATION", "questionText": "اقرأ: قل أعوذ برب الناس",
         "correctAnswer": "قل أعوذ برب الناس", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: ملك الناس",
         "correctAnswer": "ملك الناس", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: إله الناس",
         "correctAnswer": "إله الناس", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب أوائل آيات سورة الناس: ملك الناس، قل أعوذ برب الناس، إله الناس",
         "correctAnswer": "قل أعوذ برب الناس، ملك الناس، إله الناس",
         "options": ["ملك الناس", "قل أعوذ برب الناس", "إله الناس"],
         "difficultyLevel": 3, "subSkill": "memorization"},
        {"type": "SHORT_ANSWER", "questionText": "ممَّ نستعيذ في سورة الناس؟",
         "correctAnswer": "الوسواس الخناس", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "MCQ", "questionText": "كم عدد آيات سورة الناس؟",
         "correctAnswer": "ست", "options": ["أربع", "خمس", "ست", "سبع"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "سورة الناس من المعوّذتين",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "سورة الفلق": [
        {"type": "PRONUNCIATION", "questionText": "اقرأ: قل أعوذ برب الفلق",
         "correctAnswer": "قل أعوذ برب الفلق", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: من شر ما خلق",
         "correctAnswer": "من شر ما خلق", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: ومن شر غاسق إذا وقب",
         "correctAnswer": "ومن شر غاسق إذا وقب", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب أوائل آيات سورة الفلق: من شر ما خلق، قل أعوذ برب الفلق، ومن شر غاسق إذا وقب",
         "correctAnswer": "قل أعوذ برب الفلق، من شر ما خلق، ومن شر غاسق إذا وقب",
         "options": ["من شر ما خلق", "قل أعوذ برب الفلق", "ومن شر غاسق إذا وقب"],
         "difficultyLevel": 3, "subSkill": "memorization"},
        {"type": "MCQ", "questionText": "كم عدد آيات سورة الفلق؟",
         "correctAnswer": "خمس", "options": ["ثلاث", "أربع", "خمس", "ست"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "سورة الفلق تعلّمنا الاستعاذة بالله",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER", "questionText": "ما معنى الفلق؟",
         "correctAnswer": "الصبح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
    ],
    "سورة المسد": [
        {"type": "PRONUNCIATION", "questionText": "اقرأ: تبت يدا أبي لهب وتب",
         "correctAnswer": "تبت يدا أبي لهب وتب", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: ما أغنى عنه ماله وما كسب",
         "correctAnswer": "ما أغنى عنه ماله وما كسب", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "PRONUNCIATION", "questionText": "اقرأ: سيصلى ناراً ذات لهب",
         "correctAnswer": "سيصلى ناراً ذات لهب", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب آيات أول سورة المسد: ما أغنى عنه ماله وما كسب، تبت يدا أبي لهب وتب، سيصلى ناراً ذات لهب",
         "correctAnswer": "تبت يدا أبي لهب وتب، ما أغنى عنه ماله وما كسب، سيصلى ناراً ذات لهب",
         "options": ["ما أغنى عنه ماله وما كسب", "تبت يدا أبي لهب وتب", "سيصلى ناراً ذات لهب"],
         "difficultyLevel": 3, "subSkill": "memorization"},
        {"type": "MCQ", "questionText": "كم عدد آيات سورة المسد؟",
         "correctAnswer": "خمس", "options": ["ثلاث", "أربع", "خمس", "ست"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "TRUE_FALSE", "questionText": "أبو لهب كان من أعداء النبي ﷺ",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر اسم مَن ذُكر في سورة المسد",
         "correctAnswer": "أبو لهب", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "خلق الله تعالى": [
        {"type": "MCQ", "questionText": "أي مما يلي خلقه الله؟",
         "correctAnswer": "كل ما سبق",
         "options": ["السماء", "البحار", "الجبال", "كل ما سبق"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: خلق الله السماوات و___",
         "correctAnswer": "الأرض", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "كل المخلوقات الجميلة دليل على عظمة الله",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: سبحان الله الخالق العظيم",
         "correctAnswer": "سبحان الله الخالق العظيم", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب من الصغير إلى الكبير: نملة، فيل، شجرة، جبل",
         "correctAnswer": "نملة، شجرة، فيل، جبل",
         "options": ["نملة", "فيل", "شجرة", "جبل"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "إذا تأملت في الكون فماذا تتذكر؟",
         "correctAnswer": "عظمة الله",
         "options": ["نفسي فقط", "عظمة الله", "ألعابي", "أصدقائي"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر مخلوقاً في السماء",
         "correctAnswer": "النجم", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "آداب الطعام": [
        {"type": "MCQ", "questionText": "بأي يد نأكل؟",
         "correctAnswer": "اليمنى",
         "options": ["اليسرى", "اليمنى", "كلتاهما", "بالملعقة فقط"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: نقول قبل الأكل ___",
         "correctAnswer": "بسم الله", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نأكل ممَّا يلينا في الصحن",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: بسم الله",
         "correctAnswer": "بسم الله", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب آداب الطعام بالترتيب: الأكل بسم الله، غسل اليدين قبل الأكل، الحمد لله بعد الأكل",
         "correctAnswer": "غسل اليدين قبل الأكل، الأكل بسم الله، الحمد لله بعد الأكل",
         "options": ["الأكل بسم الله", "غسل اليدين قبل الأكل", "الحمد لله بعد الأكل"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "نسي صديقك أن يقول بسم الله قبل الأكل، ماذا تفعل؟",
         "correctAnswer": "أذكّره بلطف",
         "options": ["أصرخ عليه", "أتجاهل", "أذكّره بلطف", "أمنعه من الأكل"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "ماذا نقول إذا انتهينا من الطعام؟",
         "correctAnswer": "الحمد لله", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "آداب النظافة": [
        {"type": "MCQ", "questionText": "كم مرة نغسل أسناننا في اليوم على الأقل؟",
         "correctAnswer": "مرتان",
         "options": ["مرة في الأسبوع", "مرة", "مرتان", "بدون"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK", "questionText": "أكمل: ___ من الإيمان",
         "correctAnswer": "النظافة", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نغسل أيدينا قبل الأكل وبعده",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: النظافة من الإيمان",
         "correctAnswer": "النظافة من الإيمان", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب خطوات غسل اليدين: التجفيف، فتح الماء، استخدام الصابون، الفرك جيداً",
         "correctAnswer": "فتح الماء، استخدام الصابون، الفرك جيداً، التجفيف",
         "options": ["التجفيف", "فتح الماء", "استخدام الصابون", "الفرك جيداً"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "ماذا نفعل إذا اتسخت ملابسنا؟",
         "correctAnswer": "نغسلها أو نغيّرها",
         "options": ["نتركها", "نغطيها بمعطف", "نغسلها أو نغيّرها", "نسأل الجار"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "بماذا ننظف أسناننا؟",
         "correctAnswer": "بالفرشاة والمعجون", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "الرفق بالحيوان": [
        {"type": "MCQ", "questionText": "إذا رأيت قطة جائعة، ماذا تفعل؟",
         "correctAnswer": "أعطيها طعاماً وماءً",
         "options": ["أركلها", "أتجاهلها", "أعطيها طعاماً وماءً", "أصرخ عليها"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK", "questionText": "أكمل: نُحسن إلى ___",
         "correctAnswer": "الحيوان", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "إيذاء الحيوان مخالف لتعاليم الإسلام",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: ارحموا من في الأرض يرحمكم من في السماء",
         "correctAnswer": "ارحموا من في الأرض يرحمكم من في السماء", "options": None,
         "difficultyLevel": 3, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب أعمال الرحمة بالحيوان: الإطعام، إيواؤه من البرد، السقي، التخفيف عنه",
         "correctAnswer": "الإطعام، السقي، إيواؤه من البرد، التخفيف عنه",
         "options": ["الإطعام", "إيواؤه من البرد", "السقي", "التخفيف عنه"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "أي مما يلي يخالف الرفق بالحيوان؟",
         "correctAnswer": "تحميله ما لا يطيق",
         "options": ["إطعامه", "سقيه", "تحميله ما لا يطيق", "مداواته إذا مرض"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر طريقة للإحسان إلى الحيوان",
         "correctAnswer": "إطعامه", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "بر الوالدين": [
        {"type": "MCQ", "questionText": "كيف نتعامل مع الوالدين؟",
         "correctAnswer": "بالاحترام والطاعة في المعروف",
         "options": ["بالعصيان", "بالاحترام والطاعة في المعروف", "بالصراخ", "بتجاهلهما"],
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "FILL_BLANK", "questionText": "أكمل: ___ الوالدين من أعظم الأعمال",
         "correctAnswer": "بر", "options": None,
         "difficultyLevel": 2, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "نقول للوالدين: أُف",
         "correctAnswer": "خطأ", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: ربِّ ارحمهما كما ربياني صغيراً",
         "correctAnswer": "ربِّ ارحمهما كما ربياني صغيراً", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب من الأبسط إلى الأعمق في البر: مساعدتهما، الدعاء لهما، طاعتهما، رعايتهما عند الكبر",
         "correctAnswer": "طاعتهما، مساعدتهما، الدعاء لهما، رعايتهما عند الكبر",
         "options": ["مساعدتهما", "الدعاء لهما", "طاعتهما", "رعايتهما عند الكبر"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "نادتك أمك وأنت تلعب، ماذا تفعل؟",
         "correctAnswer": "أتوقف عن اللعب وأذهب إليها",
         "options": ["أكمل اللعب", "أتظاهر بعدم السماع", "أتوقف عن اللعب وأذهب إليها", "أطلب منها الانتظار طويلاً"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر طريقة لبر الأم",
         "correctAnswer": "أساعدها", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "حب الوطن": [
        {"type": "MCQ", "questionText": "ما اسم بلدنا؟",
         "correctAnswer": "فلسطين",
         "options": ["مصر", "فلسطين", "الأردن", "السودان"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: ___ الوطن من الإيمان",
         "correctAnswer": "حب", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE", "questionText": "علينا أن نحافظ على نظافة شوارع وطننا",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "application"},
        {"type": "PRONUNCIATION", "questionText": "قل: أحب وطني فلسطين",
         "correctAnswer": "أحب وطني فلسطين", "options": None,
         "difficultyLevel": 1, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب طرق خدمة الوطن: الدراسة بجد، احترام القانون، الحفاظ على نظافته، مساعدة الناس",
         "correctAnswer": "الدراسة بجد، احترام القانون، الحفاظ على نظافته، مساعدة الناس",
         "options": ["الدراسة بجد", "احترام القانون", "الحفاظ على نظافته", "مساعدة الناس"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ", "questionText": "أيها يُعدّ من حب الوطن؟",
         "correctAnswer": "الحفاظ على ممتلكاته العامة",
         "options": ["إتلاف الأشجار", "رمي القمامة", "الحفاظ على ممتلكاته العامة", "تخريب المرافق"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر مدينة في فلسطين",
         "correctAnswer": "القدس", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
    "التعاون": [
        {"type": "MCQ", "questionText": "التعاون يعني:",
         "correctAnswer": "العمل معاً لإنجاز شيء",
         "options": ["الجلوس وحدنا", "العمل معاً لإنجاز شيء", "اللعب فقط", "الأكل معاً"],
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK", "questionText": "أكمل: تعاونوا على البر و___",
         "correctAnswer": "التقوى", "options": None,
         "difficultyLevel": 2, "subSkill": "memorization"},
        {"type": "TRUE_FALSE", "questionText": "التعاون يجعل العمل أسرع وأسهل",
         "correctAnswer": "صح", "options": None,
         "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION", "questionText": "قل: تعاونوا على البر والتقوى",
         "correctAnswer": "تعاونوا على البر والتقوى", "options": None,
         "difficultyLevel": 2, "subSkill": "recitation"},
        {"type": "ORDERING", "questionText": "رتّب خطوات العمل الجماعي: تنفيذ المهام، الاتفاق على الهدف، توزيع الأدوار، تقييم النتيجة",
         "correctAnswer": "الاتفاق على الهدف، توزيع الأدوار، تنفيذ المهام، تقييم النتيجة",
         "options": ["تنفيذ المهام", "الاتفاق على الهدف", "توزيع الأدوار", "تقييم النتيجة"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "MCQ", "questionText": "زميلك في الصف لا يفهم سؤالاً. ماذا تفعل؟",
         "correctAnswer": "أساعده على فهمه",
         "options": ["أتركه", "أضحك عليه", "أساعده على فهمه", "أغيّر الموضوع"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER", "questionText": "اذكر طريقة للتعاون في البيت",
         "correctAnswer": "أساعد أمي في تنظيف الغرفة", "options": None,
         "difficultyLevel": 1, "subSkill": "production"},
    ],
}


# Both re1_p1 and re1_p2 have a lesson titled "مراجعة عامة". The shared
# ADDITIONS dict above contains the p1 review's content; we override the p2
# review with a distinct list to avoid creating cross-file R10 duplicates.
P2_REVIEW_OVERRIDE = [
    {"type": "FILL_BLANK", "questionText": "أكمل: نقول قبل الطعام ___ الله",
     "correctAnswer": "بسم", "options": None,
     "difficultyLevel": 1, "subSkill": "production"},
    {"type": "PRONUNCIATION", "questionText": "اقرأ: قل أعوذ برب الناس",
     "correctAnswer": "قل أعوذ برب الناس", "options": None,
     "difficultyLevel": 1, "subSkill": "recitation"},
    {"type": "ORDERING", "questionText": "رتّب: نأكل بسم الله، نغسل اليدين، نقول الحمد لله",
     "correctAnswer": "نغسل اليدين، نأكل بسم الله، نقول الحمد لله",
     "options": ["نأكل بسم الله", "نغسل اليدين", "نقول الحمد لله"],
     "difficultyLevel": 2, "subSkill": "application"},
    {"type": "MCQ", "questionText": "أي من التالي ليس من آداب الإسلام؟",
     "correctAnswer": "إيذاء الحيوان",
     "options": ["النظافة", "الصدق", "إيذاء الحيوان", "احترام الكبير"],
     "difficultyLevel": 3, "subSkill": "application"},
    {"type": "TRUE_FALSE", "questionText": "احترام الوالدين من أعظم العبادات",
     "correctAnswer": "صح", "options": None,
     "difficultyLevel": 1, "subSkill": "comprehension"},
    {"type": "MCQ", "questionText": "بماذا أوصانا الله تعالى تجاه الحيوان؟",
     "correctAnswer": "الرفق به",
     "options": ["إيذاؤه", "تجاهله", "الرفق به", "الخوف منه"],
     "difficultyLevel": 1, "subSkill": "comprehension"},
    {"type": "SHORT_ANSWER", "questionText": "اذكر سورة قصيرة من القرآن",
     "correctAnswer": "الإخلاص", "options": None,
     "difficultyLevel": 1, "subSkill": "production"},
]


def main():
    grand = 0
    for fname in ["re1_p1.json", "re1_p2.json"]:
        path = CURRICULUM / fname
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        added = 0
        for lesson in data.get("lessons", []):
            title = lesson.get("title")
            # File-specific override for the shared "مراجعة عامة" title:
            if title == "مراجعة عامة" and fname == "re1_p2.json":
                additions = P2_REVIEW_OVERRIDE
            elif title in ADDITIONS:
                additions = ADDITIONS[title]
            else:
                continue
            existing = {q.get("questionText") for q in lesson.get("questions", [])}
            for q in additions:
                if q["questionText"] in existing:
                    continue
                lesson["questions"].append(q)
                added += 1
        if added:
            with path.open("w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write("\n")
        print(f"  {fname}: added {added}")
        grand += added
    print(f"DONE: added {grand} religion questions")


if __name__ == "__main__":
    main()
