"""
Backfill Grade 1 English lessons (en1_p1.json + en1_p2.json):

For each of the 18 vocabulary/theme units, add 5-7 questions that:
- bring the lesson to ≥10 questions (R8)
- include ≥1 difficulty-3 question (R9)
- add ORDERING (sentence construction) and additional MCQ/FILL/PRONUNCIATION
  variety per spec §4.4

Idempotent: skips additions whose questionText already exists in the lesson.

Note on type R3 — FILL_BLANK questions MUST contain exactly one '___' marker.
The new entries use English '___' tokens to satisfy the audit.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
CURRICULUM = HERE.parent.parent / "backend" / "src" / "main" / "resources" / "curriculum"

ADDITIONS = {
    # ===== en1_p1 =====
    "Hello! (Unit 1)": [
        {"type": "MCQ",
         "questionText": "What do you say in the evening when you leave?",
         "correctAnswer": "Good evening",
         "options": ["Good morning", "Good night", "Good evening", "Hi"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate to English: مع السلامة",
         "correctAnswer": "Goodbye",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "We say 'Good night' before going to sleep",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Goodbye",
         "correctAnswer": "Goodbye",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "ORDERING",
         "questionText": "Put in order to greet: morning, Good, !",
         "correctAnswer": "Good, morning, !",
         "options": ["morning", "Good", "!"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "When meeting a teacher in the morning, the BEST greeting is:",
         "correctAnswer": "Good morning, teacher!",
         "options": ["Hi!", "Good morning, teacher!", "Bye!", "Good night!"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "My School (Unit 2)": [
        {"type": "MCQ",
         "questionText": "What is 'مسطرة' in English?",
         "correctAnswer": "Ruler",
         "options": ["Pen", "Ruler", "Eraser", "Bag"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "An eraser is used to erase pencil marks",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: School",
         "correctAnswer": "School",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate to English: ممحاة",
         "correctAnswer": "Eraser",
         "options": None, "difficultyLevel": 2, "subSkill": "production"},
        {"type": "ORDERING",
         "questionText": "Put words in order: book, This, is, a",
         "correctAnswer": "This, is, a, book",
         "options": ["book", "This", "is", "a"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Which item do you NOT bring to school?",
         "correctAnswer": "Refrigerator",
         "options": ["Pencil", "Book", "Refrigerator", "Bag"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "My Family (Unit 3)": [
        {"type": "MCQ",
         "questionText": "What is 'أم' in English?",
         "correctAnswer": "Mother",
         "options": ["Father", "Mother", "Sister", "Brother"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: My ___ is a man (parent)",
         "correctAnswer": "father",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "A 'sister' is a girl in your family",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Family",
         "correctAnswer": "Family",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "ORDERING",
         "questionText": "Put words in order: my, This, is, brother",
         "correctAnswer": "This, is, my, brother",
         "options": ["my", "This", "is", "brother"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Your mother's son is your:",
         "correctAnswer": "Brother",
         "options": ["Father", "Sister", "Brother", "Cousin"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Numbers 1-5 (Unit 4)": [
        {"type": "MCQ",
         "questionText": "How do we say '٣' in English?",
         "correctAnswer": "Three",
         "options": ["Two", "Three", "Four", "Five"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: One, two, ___, four, five",
         "correctAnswer": "three",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "'Five' comes after 'four'",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Five",
         "correctAnswer": "Five",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "ORDERING",
         "questionText": "Put in order: three, one, four, two, five",
         "correctAnswer": "one, two, three, four, five",
         "options": ["three", "one", "four", "two", "five"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "If you have two apples and add three more, how many apples do you have? (in English)",
         "correctAnswer": "Five",
         "options": ["Three", "Four", "Five", "Six"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Colors (Unit 5)": [
        {"type": "MCQ",
         "questionText": "What color is the sun?",
         "correctAnswer": "Yellow",
         "options": ["Blue", "Yellow", "Green", "Black"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: Grass is ___",
         "correctAnswer": "green",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "Snow is black",
         "correctAnswer": "False",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Blue",
         "correctAnswer": "Blue",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: أحمر",
         "correctAnswer": "Red",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Mixing red and yellow makes which color?",
         "correctAnswer": "Orange",
         "options": ["Pink", "Orange", "Purple", "Brown"],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "ORDERING",
         "questionText": "Put colors of a traffic light from top to bottom: green, yellow, red",
         "correctAnswer": "red, yellow, green",
         "options": ["green", "yellow", "red"],
         "difficultyLevel": 2, "subSkill": "application"},
    ],
    "My Body (Unit 6)": [
        {"type": "MCQ",
         "questionText": "What is 'يد' in English?",
         "correctAnswer": "Hand",
         "options": ["Foot", "Hand", "Eye", "Ear"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We see with our eyes",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I hear with my ___ (organ on the side of head)",
         "correctAnswer": "ears",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Eyes",
         "correctAnswer": "Eyes",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: قدم",
         "correctAnswer": "Foot",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which body part do you use to walk?",
         "correctAnswer": "Feet",
         "options": ["Hands", "Feet", "Eyes", "Ears"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "How many fingers does a person normally have on two hands?",
         "correctAnswer": "Ten",
         "options": ["Five", "Eight", "Ten", "Twelve"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Animals (Unit 7)": [
        {"type": "MCQ",
         "questionText": "Which animal says 'meow'?",
         "correctAnswer": "Cat",
         "options": ["Dog", "Cow", "Cat", "Bird"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "Fish live in water",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: A ___ gives us milk (large farm animal)",
         "correctAnswer": "cow",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Dog",
         "correctAnswer": "Dog",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: عصفور",
         "correctAnswer": "Bird",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which animal can fly?",
         "correctAnswer": "Bird",
         "options": ["Cow", "Bird", "Fish", "Cat"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Which is NOT a farm animal?",
         "correctAnswer": "Lion",
         "options": ["Cow", "Sheep", "Lion", "Chicken"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Food (Unit 8)": [
        {"type": "MCQ",
         "questionText": "What color is a banana?",
         "correctAnswer": "Yellow",
         "options": ["Red", "Yellow", "Green", "Blue"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "Bread is food we eat",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I drink ___ in the morning (white liquid)",
         "correctAnswer": "milk",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Bread",
         "correctAnswer": "Bread",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: ماء",
         "correctAnswer": "Water",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which is a fruit?",
         "correctAnswer": "Apple",
         "options": ["Bread", "Cheese", "Apple", "Rice"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "MCQ",
         "questionText": "Which food is healthiest for breakfast?",
         "correctAnswer": "Eggs and bread",
         "options": ["Candy", "Soda only", "Eggs and bread", "Ice cream"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Review (Unit 9)": [
        {"type": "FILL_BLANK",
         "questionText": "Complete: Three plus two equals ___",
         "correctAnswer": "five",
         "options": None, "difficultyLevel": 1, "subSkill": "computation"},
        {"type": "MCQ",
         "questionText": "What color is a banana?",
         "correctAnswer": "Yellow",
         "options": ["Red", "Yellow", "Blue", "Green"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "'Father' is a male family member",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "ORDERING",
         "questionText": "Put days in order: Tuesday, Sunday, Monday",
         "correctAnswer": "Sunday, Monday, Tuesday",
         "options": ["Tuesday", "Sunday", "Monday"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Family",
         "correctAnswer": "Family",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "MCQ",
         "questionText": "Best response to 'Hello, how are you?'",
         "correctAnswer": "I am fine, thank you.",
         "options": ["Goodbye!", "I am fine, thank you.", "What is that?", "No, thanks."],
         "difficultyLevel": 3, "subSkill": "application"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: قطة",
         "correctAnswer": "Cat",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
    ],

    # ===== en1_p2 =====
    "My House (Unit 10)": [
        {"type": "MCQ",
         "questionText": "Where do we sleep in a house?",
         "correctAnswer": "Bedroom",
         "options": ["Kitchen", "Bedroom", "Garden", "Garage"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We cook food in the kitchen",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: We watch TV in the ___ room",
         "correctAnswer": "living",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: House",
         "correctAnswer": "House",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: غرفة",
         "correctAnswer": "Room",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "ORDERING",
         "questionText": "Put words in order: my, This, is, house",
         "correctAnswer": "This, is, my, house",
         "options": ["my", "This", "is", "house"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Which room would you go to for a bath?",
         "correctAnswer": "Bathroom",
         "options": ["Bedroom", "Kitchen", "Bathroom", "Living room"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Clothes (Unit 11)": [
        {"type": "MCQ",
         "questionText": "What do you wear on your feet?",
         "correctAnswer": "Shoes",
         "options": ["Hat", "Shoes", "Shirt", "Coat"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We wear a coat in cold weather",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I wear a ___ on my head",
         "correctAnswer": "hat",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Shirt",
         "correctAnswer": "Shirt",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: قميص",
         "correctAnswer": "Shirt",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which clothing keeps you warmest?",
         "correctAnswer": "Coat",
         "options": ["T-shirt", "Coat", "Shorts", "Sandals"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "MCQ",
         "questionText": "Which clothing matches summer best?",
         "correctAnswer": "Shorts",
         "options": ["Coat", "Boots", "Shorts", "Mittens"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Numbers 6-10 (Unit 12)": [
        {"type": "MCQ",
         "questionText": "How do we say '٧' in English?",
         "correctAnswer": "Seven",
         "options": ["Six", "Seven", "Eight", "Nine"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: Six, ___, eight, nine, ten",
         "correctAnswer": "seven",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "'Ten' comes after 'nine'",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Eight",
         "correctAnswer": "Eight",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "ORDERING",
         "questionText": "Put in order: ten, six, eight, seven, nine",
         "correctAnswer": "six, seven, eight, nine, ten",
         "options": ["ten", "six", "eight", "seven", "nine"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Six plus four equals (in English):",
         "correctAnswer": "Ten",
         "options": ["Eight", "Nine", "Ten", "Eleven"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Toys (Unit 13)": [
        {"type": "MCQ",
         "questionText": "Which toy is round and we kick or throw it?",
         "correctAnswer": "Ball",
         "options": ["Doll", "Ball", "Car", "Kite"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "A doll is a toy",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I play with a toy ___ on the road (vehicle)",
         "correctAnswer": "car",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Toy",
         "correctAnswer": "Toy",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: لعبة",
         "correctAnswer": "Toy",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which toy flies in the wind?",
         "correctAnswer": "Kite",
         "options": ["Ball", "Doll", "Kite", "Car"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "MCQ",
         "questionText": "If three children share two balls equally, how many children do not have a ball?",
         "correctAnswer": "One",
         "options": ["Zero", "One", "Two", "Three"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Weather (Unit 14)": [
        {"type": "MCQ",
         "questionText": "What weather is it when the sun is shining?",
         "correctAnswer": "Sunny",
         "options": ["Rainy", "Snowy", "Sunny", "Cloudy"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We use an umbrella when it rains",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: In winter it is very ___",
         "correctAnswer": "cold",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Rain",
         "correctAnswer": "Rain",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: حار",
         "correctAnswer": "Hot",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "When it snows, the ground becomes:",
         "correctAnswer": "White",
         "options": ["Red", "Green", "Yellow", "White"],
         "difficultyLevel": 2, "subSkill": "comprehension"},
        {"type": "MCQ",
         "questionText": "Which clothes do we wear in HOT weather?",
         "correctAnswer": "T-shirt and shorts",
         "options": ["Coat and boots", "T-shirt and shorts", "Hat and gloves", "Scarf and mittens"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Fruits & Vegetables (Unit 15)": [
        {"type": "MCQ",
         "questionText": "Which is a vegetable?",
         "correctAnswer": "Carrot",
         "options": ["Apple", "Banana", "Carrot", "Orange"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "Strawberry is a fruit",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: An ___ is a red or green round fruit",
         "correctAnswer": "apple",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Tomato",
         "correctAnswer": "Tomato",
         "options": None, "difficultyLevel": 2, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: برتقالة",
         "correctAnswer": "Orange",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "Which is yellow and curved?",
         "correctAnswer": "Banana",
         "options": ["Apple", "Banana", "Tomato", "Grape"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "MCQ",
         "questionText": "Which is NOT a fruit?",
         "correctAnswer": "Potato",
         "options": ["Apple", "Banana", "Potato", "Grape"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Actions (Unit 16)": [
        {"type": "MCQ",
         "questionText": "What action do we do with our legs?",
         "correctAnswer": "Run",
         "options": ["Eat", "Read", "Run", "Sleep"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We use a book to read",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I ___ water when I am thirsty",
         "correctAnswer": "drink",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Jump",
         "correctAnswer": "Jump",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: يأكل",
         "correctAnswer": "Eat",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "ORDERING",
         "questionText": "Put words in order: I, run, fast, can",
         "correctAnswer": "I, can, run, fast",
         "options": ["I", "run", "fast", "can"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Which action belongs in a swimming pool?",
         "correctAnswer": "Swim",
         "options": ["Run", "Swim", "Sleep", "Read"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "My Day (Unit 17)": [
        {"type": "MCQ",
         "questionText": "What do we do at night?",
         "correctAnswer": "Sleep",
         "options": ["Eat breakfast", "Sleep", "Go to school", "Play"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "TRUE_FALSE",
         "questionText": "We eat breakfast in the morning",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I brush my ___ before bed",
         "correctAnswer": "teeth",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Morning",
         "correctAnswer": "Morning",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: ليل",
         "correctAnswer": "Night",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "ORDERING",
         "questionText": "Order daily activities: lunch, breakfast, dinner",
         "correctAnswer": "breakfast, lunch, dinner",
         "options": ["lunch", "breakfast", "dinner"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "MCQ",
         "questionText": "Which activity is FIRST in a typical school day?",
         "correctAnswer": "Wake up",
         "options": ["Sleep", "Have lunch", "Wake up", "Go home"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
    "Review (Unit 18)": [
        {"type": "MCQ",
         "questionText": "How many days are in one week?",
         "correctAnswer": "Seven",
         "options": ["Five", "Six", "Seven", "Eight"],
         "difficultyLevel": 1, "subSkill": "recognition"},
        {"type": "FILL_BLANK",
         "questionText": "Complete: I wear ___ on my feet",
         "correctAnswer": "shoes",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "TRUE_FALSE",
         "questionText": "A bedroom is where we sleep",
         "correctAnswer": "True",
         "options": None, "difficultyLevel": 1, "subSkill": "comprehension"},
        {"type": "PRONUNCIATION",
         "questionText": "Say the word: Water",
         "correctAnswer": "Water",
         "options": None, "difficultyLevel": 1, "subSkill": "pronunciation"},
        {"type": "ORDERING",
         "questionText": "Put words in order: I, an, eat, apple",
         "correctAnswer": "I, eat, an, apple",
         "options": ["I", "an", "eat", "apple"],
         "difficultyLevel": 2, "subSkill": "application"},
        {"type": "SHORT_ANSWER",
         "questionText": "Translate: مدرسة",
         "correctAnswer": "School",
         "options": None, "difficultyLevel": 1, "subSkill": "production"},
        {"type": "MCQ",
         "questionText": "If today is Monday, what day comes next?",
         "correctAnswer": "Tuesday",
         "options": ["Sunday", "Tuesday", "Friday", "Saturday"],
         "difficultyLevel": 3, "subSkill": "application"},
    ],
}


def main():
    grand = 0
    for fname in ["en1_p1.json", "en1_p2.json"]:
        path = CURRICULUM / fname
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        added = 0
        for lesson in data.get("lessons", []):
            title = lesson.get("title")
            if title not in ADDITIONS:
                continue
            existing = {q.get("questionText") for q in lesson.get("questions", [])}
            for q in ADDITIONS[title]:
                if q["questionText"] in existing:
                    continue
                lesson["questions"].append(q)
                added += 1
        if added:
            with path.open("w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
                f.write("\n")
        print(f"  {fname}: added {added}")
        grand += added
    print(f"DONE: added {grand} English questions")


if __name__ == "__main__":
    main()
