"""
Build Grade 2 English, Semester 2 — en2_p2.json.

9 units (continuing en2_p1 numbering):
  10. My hobbies      — likes: playing football/swimming/drawing/reading/singing
  11. Transport       — ship/plane/train/bus/van/car/bike + this/these + fast/slow
  12. Let's find out! — flag/pen/keyboard/mouse/ruler/eraser/crayon + 'can see'
  13. Let's go shopping! — sweater/socks/hat/pyjamas/boots/shirt + 'I'd like'
  14. Revision (10-13)
  15. Guess who?      — extended family + descriptions (tall/short/blonde/brown)
  16. My country      — mountain/river/town/sea + Palestine + Hebron/Haifa/Gaza/Jerusalem/Nablus + 'I'm from'
  17. Happy birthday! — candles/balloons/cake/party/present + feelings happy/sad
  18. Revision (10-17)

Same spec §4.4 template. Revision units pick PRONUNCIATION items from
Units' vocab WITHOUT reusing the same exact PRONUNCIATION questionTexts
that already appear in earlier units (R10 strict).
"""
from _common import q, write_curriculum


UNIT_10 = {
    "title": "My hobbies (Unit 10)",
    "orderIndex": 1,
    "content": "Hobbies vocabulary: playing football, dancing, swimming, drawing, reading, singing. Asking 'What do you like?' and 'What does he/she like?'.",
    "objectives": "Name common hobbies. Ask and answer about likes using 'do' and 'does'.",
    "questions": [
        q("MCQ", "What is the English word for 'سباحة'?",
          "swimming",
          ["dancing", "swimming", "reading", "singing"], 1, "recognition"),
        q("MCQ", "How do you ask Tala about her favourite hobby?",
          "What do you like?",
          ["What does she like?", "What do you like?",
           "What is your name?", "How old are you?"], 2, "application"),
        q("MCQ", "Sami likes ___ books in the evening.",
          "reading",
          ["read", "reading", "to read books", "books reading"], 2, "production"),
        q("TRUE_FALSE", "We use a ball to play football.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "Singing is a kind of food.",
          "False", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: رسم",
          "drawing", None, 1, "production"),
        q("SHORT_ANSWER", "Name one hobby you like.",
          "reading", None, 1, "production"),
        q("FILL_BLANK", "Complete: I ___ playing football. (like / likes)",
          "like", None, 1, "production"),
        q("FILL_BLANK", "Complete: She ___ singing.",
          "likes", None, 2, "production"),
        q("ORDERING", "Put in order: drawing, like, I, very, much",
          "I, like, drawing, very, much",
          ["drawing", "like", "I", "very", "much"], 2, "application"),
        q("PRONUNCIATION", "Say: football",
          "football", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: drawing",
          "drawing", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: singing",
          "singing", None, 1, "pronunciation"),
        q("MCQ", "Your friend asks 'What does your sister like?' and she loves dance. What is the BEST answer?",
          "She likes dancing.",
          ["I like dancing.", "She likes dancing.",
           "He likes dancing.", "We dancing."], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_11 = {
    "title": "Transport (Unit 11)",
    "orderIndex": 2,
    "content": "Transport vocabulary: ship, plane, train, bus, van, car, bike. 'This' and 'these'. Adjectives: fast and slow, big and small.",
    "objectives": "Name common forms of transport. Use 'this' and 'these'. Describe with fast/slow.",
    "questions": [
        q("MCQ", "What is the English word for 'طائرة'?",
          "plane",
          ["train", "plane", "ship", "bus"], 1, "recognition"),
        q("MCQ", "Which one moves on water?",
          "ship",
          ["car", "plane", "ship", "bike"], 1, "comprehension"),
        q("MCQ", "Pick the correct form: ___ cars are slow.",
          "These",
          ["This", "These", "It", "Is"], 2, "production"),
        q("TRUE_FALSE", "A plane is faster than a bike.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "A bike has four wheels.",
          "False", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: حافلة",
          "bus", None, 1, "production"),
        q("SHORT_ANSWER", "Which transport flies in the sky?",
          "plane", None, 1, "production"),
        q("FILL_BLANK", "Complete: ___ ship is very fast.",
          "This", None, 1, "production"),
        q("FILL_BLANK", "Complete: This car is ___ (opposite of fast).",
          "slow", None, 2, "production"),
        q("ORDERING", "Put in order: fast, very, this, plane, is",
          "this, plane, is, very, fast",
          ["fast", "very", "this", "plane", "is"], 2, "application"),
        q("PRONUNCIATION", "Say: train",
          "train", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: bicycle",
          "bicycle", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: ship",
          "ship", None, 1, "pronunciation"),
        q("MCQ", "You want to go from Hebron to a small village nearby. Which transport is best?",
          "car or bus",
          ["plane", "ship", "car or bus", "train across the sea"],
          3, "application"),
    ],
    "imageUrls": [],
}

UNIT_12 = {
    "title": "Let's find out! (Unit 12)",
    "orderIndex": 3,
    "content": "Classroom items: flag, pen, keyboard, mouse, ruler, eraser, crayon. Saying 'What can you see? I can see a flag.' Using 'next to'.",
    "objectives": "Name common classroom items. Use 'can see' and prepositions.",
    "questions": [
        q("MCQ", "What is the English word for 'ممحاة'?",
          "eraser",
          ["ruler", "eraser", "crayon", "pen"], 1, "recognition"),
        q("MCQ", "Which item do you use with a computer to click?",
          "mouse",
          ["mouse", "ruler", "flag", "eraser"], 1, "comprehension"),
        q("MCQ", "How do you ask a friend what they see in a picture?",
          "What can you see?",
          ["What can you see?", "What is your name?",
           "Where is the flag?", "Are you a student?"], 1, "application"),
        q("TRUE_FALSE", "A flag is something we wave on a national day.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "A keyboard is a kind of food.",
          "False", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: مسطرة",
          "ruler", None, 1, "production"),
        q("SHORT_ANSWER", "Name one thing you put inside a pencil case.",
          "eraser", None, 2, "production"),
        q("FILL_BLANK", "Complete: I can ___ a Palestinian flag in the picture.",
          "see", None, 1, "production"),
        q("FILL_BLANK", "Complete: The mouse is ___ to the keyboard.",
          "next", None, 2, "production"),
        q("ORDERING", "Put in order: I, see, a, flag, can",
          "I, can, see, a, flag",
          ["I", "see", "a", "flag", "can"], 2, "application"),
        q("PRONUNCIATION", "Say: keyboard",
          "keyboard", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: ruler",
          "ruler", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: crayon",
          "crayon", None, 2, "pronunciation"),
        q("MCQ", "Your teacher says 'Find the eraser'. Where is it likely to be?",
          "in the pencil case next to the ruler",
          ["on the roof of the school",
           "in the pencil case next to the ruler",
           "inside the keyboard",
           "in the playground"], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_13 = {
    "title": "Let's go shopping! (Unit 13)",
    "orderIndex": 4,
    "content": "Clothes vocabulary: sweater, socks, hat, pyjamas, boots, shirt. Saying 'I'd like a new sweater'. Describing clothes with colours.",
    "objectives": "Name common clothes. Ask for items in a shop using 'I'd like'. Describe clothes with colours and size.",
    "questions": [
        q("MCQ", "What do we wear on our feet inside boots?",
          "socks",
          ["socks", "hat", "shirt", "sweater"], 1, "recognition"),
        q("MCQ", "What do we wear on our head?",
          "hat",
          ["hat", "boots", "socks", "pyjamas"], 1, "recognition"),
        q("MCQ", "You want to buy a new shirt. What do you say to the shopkeeper?",
          "I'd like a new shirt, please.",
          ["I'd like a new shirt, please.",
           "Give me!",
           "I don't want anything.",
           "Where is the shirt?"], 2, "application"),
        q("TRUE_FALSE", "Boots are warm shoes we wear in winter.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "Pyjamas are special clothes we wear to school.",
          "False", None, 2, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: قميص",
          "shirt", None, 1, "production"),
        q("SHORT_ANSWER", "What clothes do you wear to sleep?",
          "pyjamas", None, 1, "production"),
        q("FILL_BLANK", "Complete: My sweater is ___ (the opposite of big).",
          "small", None, 1, "production"),
        q("FILL_BLANK", "Complete: I'd ___ a new hat, please.",
          "like", None, 2, "production"),
        q("ORDERING", "Put in order: like, I'd, please, hat, a, new",
          "I'd, like, a, new, hat, please",
          ["like", "I'd", "please", "hat", "a", "new"], 3, "application"),
        q("PRONUNCIATION", "Say: sweater",
          "sweater", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: boots",
          "boots", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: pyjamas",
          "pyjamas", None, 2, "pronunciation"),
        q("MCQ", "It is very cold outside today. Which item should you wear?",
          "a warm sweater and boots",
          ["pyjamas only",
           "a warm sweater and boots",
           "a hat and socks for the beach",
           "nothing extra"], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_14 = {
    "title": "Revision Units 10-13 (Unit 14)",
    "orderIndex": 5,
    "content": "Review: hobbies, transport, classroom items, clothes.",
    "objectives": "Review the language and vocabulary from Units 10-13.",
    "questions": [
        q("MCQ", "Which one is NOT a hobby?",
          "boots",
          ["dancing", "singing", "swimming", "boots"], 1, "recognition"),
        q("MCQ", "Which one is a means of transport?",
          "van",
          ["van", "flag", "eraser", "sweater"], 1, "recognition"),
        q("MCQ", "Choose the correct sentence: 'She likes ___.'",
          "reading",
          ["read", "reading", "to read books always", "reads"],
          2, "production"),
        q("TRUE_FALSE", "A keyboard is part of a computer.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "Pyjamas are clothes we wear to bed.",
          "True", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: قطار",
          "train", None, 1, "production"),
        q("SHORT_ANSWER", "Name one thing you wear in winter.",
          "sweater", None, 2, "production"),
        q("FILL_BLANK", "Complete: I'd ___ a new pencil, please.",
          "like", None, 1, "production"),
        q("FILL_BLANK", "Complete: He ___ playing football. (likes / like)",
          "likes", None, 2, "production"),
        q("ORDERING", "Put in order: like, swimming, I",
          "I, like, swimming",
          ["like", "swimming", "I"], 2, "application"),
        q("PRONUNCIATION", "Say: dancing",
          "dancing", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: shirt",
          "shirt", None, 1, "pronunciation"),
        q("MCQ", "You are at a shop and want to buy two items: a sweater and socks. What do you say?",
          "I'd like a sweater and socks, please.",
          ["Give me!",
           "I'd like a sweater and socks, please.",
           "Where is the rice?",
           "I don't like."], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_15 = {
    "title": "Guess who? (Unit 15)",
    "orderIndex": 6,
    "content": "Extended family: grandfather, grandmother, cousin, dad, mum, brother, sister. Describing people: tall, short, blonde hair, brown eyes.",
    "objectives": "Name extended family members. Describe people by height, hair colour, and eye colour.",
    "questions": [
        q("MCQ", "What is 'جد' in English?",
          "grandfather",
          ["father", "grandfather", "uncle", "brother"], 1, "recognition"),
        q("MCQ", "What is 'ابن العم' in English?",
          "cousin",
          ["brother", "cousin", "uncle", "friend"], 2, "recognition"),
        q("MCQ", "Tala has black hair. Her friend Sara has yellow hair. We say Sara has ___ hair.",
          "blonde",
          ["blonde", "brown", "black", "green"], 2, "production"),
        q("TRUE_FALSE", "Your father's mother is your grandmother.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "A short person is the same as a tall person.",
          "False", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: جدّة",
          "grandmother", None, 1, "production"),
        q("SHORT_ANSWER", "Describe yourself: I have ___ hair (use a colour).",
          "brown", None, 1, "production"),
        q("FILL_BLANK", "Complete: He's very ___ (opposite of short).",
          "tall", None, 2, "production"),
        q("FILL_BLANK", "Complete: She ___ blue eyes.",
          "has", None, 2, "production"),
        q("ORDERING", "Put in order: hair, has, black, she",
          "she, has, black, hair",
          ["hair", "has", "black", "she"], 2, "application"),
        q("PRONUNCIATION", "Say: grandfather",
          "grandfather", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: cousin",
          "cousin", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: brown",
          "brown", None, 1, "pronunciation"),
        q("MCQ", "Sami is 130 cm tall, Adam is 110 cm tall. Which sentence is correct?",
          "Sami is taller than Adam.",
          ["Adam is taller than Sami.",
           "Sami is taller than Adam.",
           "They are the same height.",
           "Adam is the oldest."], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_16 = {
    "title": "My country (Unit 16)",
    "orderIndex": 7,
    "content": "Country: Palestine. Cities: Hebron, Haifa, Bethlehem, Gaza, Jerusalem, Nablus. Nature vocabulary: mountain, river, town, tree, flower, the sea. 'Where are you from? I'm from ...'.",
    "objectives": "Name the country Palestine and major cities. Use 'I'm from' to say where you live.",
    "questions": [
        q("MCQ", "What is the name of our country?",
          "Palestine",
          ["Palestine", "Jordan", "Egypt", "Lebanon"], 1, "comprehension"),
        q("MCQ", "Which city is the capital of Palestine?",
          "Jerusalem",
          ["Hebron", "Jerusalem", "Gaza", "Haifa"], 1, "comprehension"),
        q("MCQ", "How do you tell someone you live in Nablus?",
          "I'm from Nablus.",
          ["I'm from Nablus.", "He's from Nablus.",
           "Nablus is here.", "Nablus is fast."], 2, "application"),
        q("TRUE_FALSE", "Bethlehem is a Palestinian city.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "A mountain is smaller than a flower.",
          "False", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: نهر",
          "river", None, 1, "production"),
        q("SHORT_ANSWER", "Name a Palestinian city by the sea.",
          "Haifa", None, 2, "production"),
        q("FILL_BLANK", "Complete: I'm ___ Palestine.",
          "from", None, 1, "production"),
        q("FILL_BLANK", "Complete: Hebron is a city in ___.",
          "Palestine", None, 1, "production"),
        q("ORDERING", "Put in order: am, I, Hebron, from",
          "I, am, from, Hebron",
          ["am", "I", "Hebron", "from"], 2, "application"),
        q("PRONUNCIATION", "Say: Palestine",
          "Palestine", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: Jerusalem",
          "Jerusalem", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: mountain",
          "mountain", None, 2, "pronunciation"),
        q("MCQ", "Your friend in another country asks: 'Where are you from?'. You live in Gaza. Best answer?",
          "I'm from Gaza, in Palestine.",
          ["I'm Gaza.",
           "I'm from Gaza, in Palestine.",
           "Gaza is from me.",
           "I like Gaza."], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_17 = {
    "title": "Happy birthday! (Unit 17)",
    "orderIndex": 8,
    "content": "Birthday vocabulary: candles, balloons, cake, party, birthday, present. Asking 'How do you feel?' and answering 'I feel happy/sad'.",
    "objectives": "Name birthday items. Talk about feelings using 'I feel ...'.",
    "questions": [
        q("MCQ", "What do we put on a birthday cake to blow out?",
          "candles",
          ["balloons", "candles", "presents", "boots"], 1, "recognition"),
        q("MCQ", "What do you say to a friend on his birthday?",
          "Happy birthday!",
          ["Happy birthday!", "Goodbye!",
           "Be quiet!", "Where are you?"], 1, "comprehension"),
        q("MCQ", "When you get a nice gift, you feel ___.",
          "happy",
          ["sad", "happy", "tired", "hungry"], 1, "comprehension"),
        q("TRUE_FALSE", "Balloons are usually colourful and float in the air.",
          "True", None, 1, "comprehension"),
        q("TRUE_FALSE", "A birthday present is something we give and receive.",
          "True", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: حفلة",
          "party", None, 1, "production"),
        q("SHORT_ANSWER", "Describe how you feel when you lose your toy.",
          "sad", None, 2, "production"),
        q("FILL_BLANK", "Complete: I ___ happy today!",
          "feel", None, 1, "production"),
        q("FILL_BLANK", "Complete: We blow out ___ on the cake.",
          "candles", None, 1, "production"),
        q("ORDERING", "Put in order: birthday, ! , happy",
          "happy, birthday, !",
          ["birthday", "!", "happy"], 1, "application"),
        q("PRONUNCIATION", "Say: balloons",
          "balloons", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: present",
          "present", None, 1, "pronunciation"),
        q("PRONUNCIATION", "Say: cake",
          "cake", None, 1, "pronunciation"),
        q("MCQ", "Your friend is sad because he lost his toy. What is the BEST thing to say?",
          "I'm sorry. Let me help you find it.",
          ["Happy birthday!",
           "I'm sorry. Let me help you find it.",
           "Be quiet!",
           "Don't tell me."], 3, "application"),
    ],
    "imageUrls": [],
}

UNIT_18 = {
    "title": "Revision Units 10-17 (Unit 18)",
    "orderIndex": 9,
    "content": "Wide review: hobbies, transport, classroom items, clothes, family, country, birthday.",
    "objectives": "Review the language and vocabulary from Units 10-17.",
    "questions": [
        q("MCQ", "Which one is a family member?",
          "uncle",
          ["uncle", "ruler", "balloon", "river"], 1, "recognition"),
        q("MCQ", "Which is the capital of Palestine?",
          "Jerusalem",
          ["Gaza", "Jerusalem", "Hebron", "Nablus"], 2, "recognition"),
        q("MCQ", "Choose the correct sentence: '___ from Bethlehem.'",
          "I'm",
          ["I'm", "I are", "I has", "I like"], 2, "production"),
        q("TRUE_FALSE", "Pyjamas are clothes for school.",
          "False", None, 1, "comprehension"),
        q("TRUE_FALSE", "A train moves on rails.",
          "True", None, 1, "comprehension"),
        q("SHORT_ANSWER", "Translate to English: عمّ",
          "uncle", None, 1, "production"),
        q("SHORT_ANSWER", "Name one item we use to celebrate a birthday.",
          "cake", None, 2, "production"),
        q("FILL_BLANK", "Complete: She ___ green eyes.",
          "has", None, 1, "production"),
        q("FILL_BLANK", "Complete: I'd ___ a new bike, please.",
          "like", None, 2, "production"),
        q("ORDERING", "Put in order: am, from, Haifa, I",
          "I, am, from, Haifa",
          ["am", "from", "Haifa", "I"], 2, "application"),
        q("PRONUNCIATION", "Say: Bethlehem",
          "Bethlehem", None, 2, "pronunciation"),
        q("PRONUNCIATION", "Say: party",
          "party", None, 1, "pronunciation"),
        q("MCQ", "Today is your brother's birthday. He is six years old. Which is a kind sentence to say?",
          "Happy birthday! How do you feel?",
          ["Goodbye!",
           "Happy birthday! How do you feel?",
           "Be quiet!",
           "I don't know."], 3, "application"),
    ],
    "imageUrls": [],
}


LESSONS = [UNIT_10, UNIT_11, UNIT_12, UNIT_13, UNIT_14,
           UNIT_15, UNIT_16, UNIT_17, UNIT_18]


def main():
    write_curriculum(subject_code="en", grade=2, semester=2, lessons=LESSONS)


if __name__ == "__main__":
    main()
